<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Aspek extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login","refresh");
		}
        $this->load->model('Aspek_model');
		$this->load->model('Sub_praktikum_model');
    } 

    /*
     * Listing of aspek
     */
    function index()
    {
        $data['aspek'] = $this->Aspek_model->get_all_aspek();

        $data['_view'] = 'aspek/index';
		$data['judulform'] = 'ASPEK';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new aspek
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_aspek','Nama Aspek','required');
		$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_aspek' => $this->input->post('nama_aspek',TRUE),
				'kd_sub_praktikum' => $this->input->post('kd_sub_praktikum',TRUE),
				'diinput_oleh' => $_SESSION['username_admin'],
            );
            
            $aspek_id = $this->Aspek_model->add_aspek($params);
			$this->session->set_flashdata('success', 'Aspek sudah ditambahkan.');
			
            $data['_view'] = 'aspek/add';
			$data['judulform'] = 'ASPEK';
			$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();
            $this->load->view('layouts/main',$data);
			//redirect('aspek/add');
        }
        else
        {            
            $data['_view'] = 'aspek/add';
			$data['judulform'] = 'ASPEK';
			$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a aspek
     */
    function edit($id_aspek)
    {   
        // check if the aspek exists before trying to edit it
        $data['aspek'] = $this->Aspek_model->get_aspek($id_aspek);
        
        if(isset($data['aspek']['id_aspek']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_aspek','Nama Aspek','required');
			$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_aspek' => $this->input->post('nama_aspek',TRUE),
					'kd_sub_praktikum' => $this->input->post('kd_sub_praktikum',TRUE),
					'diupdate_oleh' => $_SESSION['username_admin'],
                );

                $this->Aspek_model->update_aspek($id_aspek,$params);            
                redirect('aspek/index');
            }
            else
            {
                $data['_view'] = 'aspek/edit';
				$data['judulform'] = 'ASPEK';
				$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The aspek you are trying to edit does not exist.');
    } 

    /*
     * Deleting aspek
     */
    function remove($id_aspek)
    {
        $aspek = $this->Aspek_model->get_aspek($id_aspek);

        // check if the aspek exists before trying to delete it
        if(isset($aspek['id_aspek']))
        {
            $this->Aspek_model->delete_aspek($id_aspek);
            redirect('aspek/index');
        }
        else
            show_error('The aspek you are trying to delete does not exist.');
    }
    
}
