<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Dosen_mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['kode_dosen']) ? $_SESSION['kode_dosen']:'';
		if($session==""){
			redirect("login","refresh");
		}
        $this->load->model('Mahasiswa_model');
		$this->load->model('Nilai_model');
    } 

	function input_nilai_mahasiswa()
    {
		$this->load->library('form_validation');
		
		$this->form_validation->set_rules('id_konf','Thn Akademik & Semester','required');

		$this->load->model('Dosen_model');
		$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
		
		$this->load->model('M_konfigurasi_model');
		$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
		
		$this->load->model('Mahasiswa_model');
		$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi();

		$this->load->model('Sub_praktikum_model');
		$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();

		$this->load->model('Pasien_model');
		$data['all_pasien'] = $this->Pasien_model->get_all_pasien();
		
		if($this->form_validation->run())     
		{   
			$data['show_listing'] = true;
			
			$pencarian = " a.kode_dosen=? ";
			$value = array($_SESSION['kode_dosen']);

			if($this->input->post('id_konf', TRUE) != null){
				$pencarian .= " and a.kd_konfigurasi=? ";
				array_push($value, $this->input->post('id_konf', TRUE));
			}
			
			if($this->input->post('nim', TRUE)<>""){
				$pencarian .= " and a.nim=? ";
				array_push($value, $this->input->post('nim', TRUE));
			}

			if($this->input->post('kd_sub_praktikum', TRUE)<>""){
				$pencarian .= " and a.kd_sub_praktikum=? ";
				array_push($value, $this->input->post('kd_sub_praktikum', TRUE));
			}

			if($this->input->post('nik', TRUE)<>""){
				$pencarian .= " and a.nik=? ";				
				array_push($value, $this->input->post('nik', TRUE));
			}

			if($this->input->post('tanggal_praktek', TRUE)<>""){
				$pencarian .= " and a.tanggal_praktek=? ";
				array_push($value, $this->input->post('tanggal_praktek', TRUE));
			}
			
			
			$data['listing_mahasiswa'] = $this->db->query("select a.* , b.nama_mahasiswa, c.nama_dosen, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester, g.nama_pasien
			from tbl_praktikum_mahasiswa a 
			join tbl_mahasiswa b on a.nim=b.nim
			join tbl_dosen c on a.kode_dosen=c.kode_dosen
			join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
			join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
			join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf
			join tbl_pasien g on a.nik = g.nik_pasien
			where $pencarian ", $value)->result_array();
			
			$data['_view'] = 'dosen_mahasiswa/input_nilai_mahasiswa';
			$data['judulform'] = 'INPUT NILAI MAHASISWA';
			$this->load->view('layouts/main_dosen',$data);
		}else{
			$data['show_listing'] = false;
	
			$data['_view'] = 'dosen_mahasiswa/input_nilai_mahasiswa';
			$data['judulform'] = 'INPUT NILAI MAHASISWA';
			$this->load->view('layouts/main_dosen',$data);
		}
		
	}

	function hapus_nilai($id_daftar_praktikum)
    {
        $nilai_praktek = $this->db->query("select * from tbl_praktikum_mahasiswa where kode_dosen=? and id_daftar_praktikum=?", array($_SESSION['kode_dosen'], $id_daftar_praktikum))->row_array();

        // check if the nilai_praktek exists before trying to delete it
        if(isset($nilai_praktek['id_daftar_praktikum']))
        {
			$this->db->delete('tbl_praktikum_mahasiswa',array('id_daftar_praktikum'=>$id_daftar_praktikum));
			$this->session->set_flashdata('success', 'Daftar praktikum mahasiswa sudah dihapus.');
            redirect('dosen_mahasiswa/input_nilai_mahasiswa');
        }
        else
            show_error('The daftar praktikum mahasiswa you are trying to delete does not exist.');
	}
	
	function nilai_mahasiswa()
    {
		$this->load->library('form_validation');
		
		$this->form_validation->set_rules('id_konf','Thn Akademik & Semester','required');

		$this->load->model('Dosen_model');
		$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
		
		$this->load->model('M_konfigurasi_model');
		$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
		
		$this->load->model('Mahasiswa_model');
		$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi();

		$this->load->model('Sub_praktikum_model');
		$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();

		$this->load->model('Pasien_model');
		$data['all_pasien'] = $this->Pasien_model->get_all_pasien();
		
		if($this->form_validation->run())     
		{   
			$data['show_listing'] = true;
			
			$pencarian = " a.kode_dosen=? ";
			$value = array($_SESSION['kode_dosen']);

			if($this->input->post('id_konf', TRUE) != null){
				$pencarian .= " and a.kd_konfigurasi=? ";
				array_push($value, $this->input->post('id_konf', TRUE));
			}
			
			if($this->input->post('nim', TRUE)<>""){
				$pencarian .= " and a.nim=? ";
				array_push($value, $this->input->post('nim', TRUE));
			}

			if($this->input->post('semester', TRUE)<>""){
				$pencarian .= " and a.semester=? ";
				array_push($value, $this->input->post('semester', TRUE));
			}

			if($this->input->post('kd_sub_praktikum', TRUE)<>""){
				$pencarian .= " and a.kd_sub_praktikum=? ";
				array_push($value, $this->input->post('kd_sub_praktikum', TRUE));
			}

			if($this->input->post('nik', TRUE)<>""){
				$pencarian .= " and a.nik=? ";				
				array_push($value, $this->input->post('nik', TRUE));
			}

			if($this->input->post('tanggal_praktek', TRUE)<>""){
				$pencarian .= " and a.tanggal_praktek=? ";
				array_push($value, $this->input->post('tanggal_praktek', TRUE));
			}
			
			
			$data['listing_mahasiswa'] = $this->db->query("select a.id_daftar_praktikum, a.nim, a.kode_dosen, a.kd_sub_praktikum, a.kd_konfigurasi, a.semester, g.nilai_rata,
			b.nama_mahasiswa, c.nama_dosen, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester, a.diagnosa_pasien, a.diagnosa_odontogram
						from tbl_praktikum_mahasiswa a 
						join tbl_mahasiswa b on a.nim=b.nim
						join tbl_dosen c on a.kode_dosen=c.kode_dosen
						join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
						join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
						join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf 
						join (select nim as nim_r, kd_konfigurasi as kd_konfigurasi_r, kd_sub_praktikum as kd_sub_praktikum_r, AVG(nilai) as nilai_rata 
							  from tbl_praktikum_mahasiswa group by nim, kd_konfigurasi, kd_sub_praktikum) g on a.nim=g.nim_r and a.kd_konfigurasi=g.kd_konfigurasi_r and a.kd_sub_praktikum=g.kd_sub_praktikum_r
			where $pencarian 
			group by a.nim, a.kd_konfigurasi, a.kd_sub_praktikum, a.kode_dosen", $value)->result_array();

			
			
			$data['_view'] = 'dosen_mahasiswa/nilai_mahasiswa';
			$data['judulform'] = 'NILAI MAHASISWA';
			$this->load->view('layouts/main_dosen',$data);
			

		}else{
			$data['show_listing'] = false;
	
			$data['_view'] = 'dosen_mahasiswa/nilai_mahasiswa';
			$data['judulform'] = 'NILAI MAHASISWA';
			$this->load->view('layouts/main_dosen',$data);
		}
		
	}

	function nilai_mahasiswa_detail($nim=null, $ta=null, $kd_sub_praktikum=null){
		$data['data_mahasiswa'] = $this->db->query("select a.nim, b.nama_mahasiswa, b.jk, b.hp, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester, a.kd_konfigurasi 
		from tbl_praktikum_mahasiswa a 
		join tbl_mahasiswa b on a.nim=b.nim
		join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
		join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
		join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf
		where a.nim=? and a.kd_konfigurasi=? and a.kd_sub_praktikum=?", array($nim, $ta, $kd_sub_praktikum))->row_array();
		
		$data['listing_mahasiswa'] = $this->db->query("select a.*,
		b.nama_mahasiswa, c.nama_dosen, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester, g.nama_pasien
					from tbl_praktikum_mahasiswa a 
					join tbl_mahasiswa b on a.nim=b.nim
					join tbl_dosen c on a.kode_dosen=c.kode_dosen
					join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
					join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
					join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf
					join tbl_pasien g on a.nik=g.nik_pasien
		where a.nim=? and a.kd_konfigurasi=? and a.kd_sub_praktikum=?", array($nim, $ta, $kd_sub_praktikum))->result_array();

		$data['_view'] = 'dosen_mahasiswa/nilai_mahasiswa_detail';
		$data['judulform'] = 'DETAIL NILAI MAHASISWA';
		$this->load->view('layouts/main_dosen',$data);
	}

	function nilai_mahasiswa_input($nim=null, $ta=null, $kd_sub_praktikum=null, $id_daftar_praktikum=null){
		$data['data_mahasiswa'] = $this->db->query("select a.id_daftar_praktikum, a.nim, b.nama_mahasiswa, b.jk, b.hp, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester, a.kd_konfigurasi, g.nama_pasien, a.kd_sub_praktikum, a.kd_konfigurasi, a.nik, a.tanggal_praktek, a.diagnosa_pasien, a.diagnosa_odontogram 
		from tbl_praktikum_mahasiswa a 
		join tbl_mahasiswa b on a.nim=b.nim
		join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
		join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
		join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf
		join tbl_pasien g on a.nik=g.nik_pasien
		where a.nim=? and a.kd_konfigurasi=? and a.kd_sub_praktikum=? and a.id_daftar_praktikum=?", array($nim, $ta, $kd_sub_praktikum, $id_daftar_praktikum))->row_array();

		// var_dump($data['data_mahasiswa']);
		
		$this->load->model('Sub_aspek_model');
		$data['sub_aspek'] = $this->Sub_aspek_model->get_all_sub_aspek_sub_praktikum($kd_sub_praktikum);

		$data['show_form'] = false;
		$data['_view'] = 'dosen_mahasiswa/nilai_mahasiswa_input';
		$data['judulform'] = 'INPUT NILAI MAHASISWA';
		$this->load->view('layouts/main_dosen',$data);
	}

	function nilai_mahasiswa_simpan(){
		$this->load->library('form_validation');
		
		$this->form_validation->set_rules('id_konf','Thn Akademik & Semester','required');
		$this->form_validation->set_rules('nim','Nama Mahasiswa','required');
		$this->form_validation->set_rules('nik','Nama Pasien','required');
		//$this->form_validation->set_rules('kode_dosen','Nama Dosen','required');
		$this->form_validation->set_rules('tanggal_praktek','Tanggal Praktek','required');
		$this->form_validation->set_rules('jumlah','Jumlah Sub Aspek','required');
		$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		
		if($this->form_validation->run())     
		{   
			// insert ke tabel diagnosa
			$params_diagnosa = array(
							'id_sub_praktikum' 	=> $this->input->post('kd_sub_praktikum', TRUE),
							'nik_pasien' 		=> $this->input->post('nik', TRUE),
							'nim' 				=> $this->input->post('nim', TRUE),
							'diagnosa' 			=> $this->input->post('diagnosa', TRUE),
							'kd_daftar_praktikum' => $this->input->post('kd_daftar_praktikum', TRUE),
							'diinput_oleh' 		=> $_SESSION['kode_dosen']
							);
			$this->db->insert('tbl_diagnosa', $params_diagnosa);
			
			// insert ke tabel nilai praktek
			$this->db->trans_begin();
			$params = array();
			for($i=1;$i<$this->input->post('jumlah', TRUE);$i++){
				$params[$i]['tanggal_praktek'] 		= $this->input->post('tanggal_praktek', TRUE);
				$params[$i]['nim'] 					= $this->input->post('nim', TRUE);
				$params[$i]['nik'] 					= $this->input->post('nik', TRUE);
				$params[$i]['kode_dosen'] 			= $_SESSION['kode_dosen'];
				$params[$i]['kd_sub_aspek'] 		= $_POST['kd_sub_aspek'.$i];
				$params[$i]['angka_perolehan'] 		= $_POST['angka_perolehan'.$i];
				$params[$i]['tanggal_input'] 		= date('Y-m-d');
				$params[$i]['kd_konfigurasi'] 		= $this->input->post('id_konf', TRUE);
				$params[$i]['diinput_oleh'] 		= $_SESSION['kode_dosen'];
				$params[$i]['kd_daftar_praktikum'] 	= $this->input->post('kd_daftar_praktikum', TRUE);
			}
			$this->db->insert_batch('tbl_nilai_praktek', $params);
			
			if ($this->db->trans_status() === FALSE){
				$this->db->trans_rollback();
				$this->session->set_flashdata('error', 'Nilai gagal diinput');
			} else {
				$this->db->trans_commit();
				$this->session->set_flashdata('success', 'Nilai sudah ditambahkan');
			}
			$this->db->trans_complete();

			redirect("dosen_mahasiswa/detail/".$this->input->post('nim', TRUE)."/".$this->input->post('kd_sub_praktikum', TRUE)."/".$this->input->post('id_konf', TRUE)."/".$this->input->post('kd_daftar_praktikum', TRUE),'refresh');
		}else{
			echo validation_errors();
		}
	}

	function nilai_mahasiswa_ubah($nim=null, $ta=null, $kd_sub_praktikum=null, $id_daftar_praktikum=null){
		$data['data_mahasiswa'] = $this->db->query("select a.id_daftar_praktikum, a.nim, b.nama_mahasiswa, b.jk, b.hp, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester, a.kd_konfigurasi, g.nama_pasien, a.kd_sub_praktikum, a.kd_konfigurasi, a.nik, a.tanggal_praktek 
		from tbl_praktikum_mahasiswa a 
		join tbl_mahasiswa b on a.nim=b.nim
		join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
		join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
		join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf
		join tbl_pasien g on a.nik=g.nik_pasien
		where a.nim=? and a.kd_konfigurasi=? and a.kd_sub_praktikum=? and a.id_daftar_praktikum=?", array($nim, $ta, $kd_sub_praktikum, $id_daftar_praktikum))->row_array();
				
		$data['sub_aspek'] = $this->db->query("select b.*, c.*, d.*, e.*, f.angka_perolehan, f.id_nilai_praktek 
		from tbl_sub_aspek b
		join tbl_aspek c on b.kd_aspek = c.id_aspek
		join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
		join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
		join (select id_nilai_praktek, kd_sub_aspek, angka_perolehan from tbl_nilai_praktek where nim='$nim' and kd_konfigurasi='$ta' and kd_daftar_praktikum='$id_daftar_praktikum' and kode_dosen='$_SESSION[kode_dosen]') f on b.id_sub_aspek=f.kd_sub_aspek
		where d.id_sub_praktikum=?
		order by kd_aspek, id_sub_aspek asc", array($kd_sub_praktikum))->result_array();

		$data['diagnosa'] = $this->db->query("select * from tbl_diagnosa where nim=? and kd_daftar_praktikum=?", array($nim, $id_daftar_praktikum))->row_array();
		
		$data['show_form'] = false;
		$data['_view'] = 'dosen_mahasiswa/nilai_mahasiswa_ubah';
		$data['judulform'] = 'INPUT NILAI MAHASISWA';
		$this->load->view('layouts/main_dosen',$data);
	}

	function nilai_mahasiswa_simpan_ubah(){
		$this->load->library('form_validation');
		
		$this->form_validation->set_rules('id_konf','Thn Akademik & Semester','required');
		$this->form_validation->set_rules('nim','Nama Mahasiswa','required');
		$this->form_validation->set_rules('nik','Nama Pasien','required');
		//$this->form_validation->set_rules('kode_dosen','Nama Dosen','required');
		$this->form_validation->set_rules('tanggal_praktek','Tanggal Praktek','required');
		$this->form_validation->set_rules('jumlah','Jumlah Sub Aspek','required');
		$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		
		if($this->form_validation->run())     
		{   
			// update ke tabel diagnosa
			$this->db->query("update tbl_diagnosa set diagnosa=? where id_sub_praktikum=? and nim=? and kd_daftar_praktikum=?", array($this->input->post('diagnosa', TRUE), $this->input->post('kd_sub_praktikum', TRUE), $this->input->post('nim', TRUE), $this->input->post('kd_daftar_praktikum', TRUE)));
			
			// insert ke tabel nilai praktek
			$this->db->trans_begin();
			$params = array();
			for($i=1;$i<$this->input->post('jumlah', TRUE);$i++){
				$params[$i]['tanggal_praktek'] 		= $this->input->post('tanggal_praktek', TRUE);
				$params[$i]['nim'] 					= $this->input->post('nim', TRUE);
				$params[$i]['nik'] 					= $this->input->post('nik', TRUE);
				$params[$i]['kode_dosen'] 			= $_SESSION['kode_dosen'];
				$params[$i]['kd_sub_aspek'] 		= $_POST['kd_sub_aspek'.$i];
				$params[$i]['angka_perolehan'] 		= $_POST['angka_perolehan'.$i];
				$params[$i]['id_nilai_praktek'] 	= $_POST['id_nilai_praktek'.$i];
				$params[$i]['tanggal_input'] 		= date('Y-m-d');
				$params[$i]['kd_konfigurasi'] 		= $this->input->post('id_konf', TRUE);
				$params[$i]['diinput_oleh'] 		= $_SESSION['kode_dosen'];
				$params[$i]['kd_daftar_praktikum'] 	= $this->input->post('kd_daftar_praktikum', TRUE);
			}
			$this->db->update_batch('tbl_nilai_praktek', $params, 'id_nilai_praktek');
			
			if ($this->db->trans_status() === FALSE){
				$this->db->trans_rollback();
				$this->session->set_flashdata('error', 'Nilai gagal diperbarui');
			} else {
				$this->db->trans_commit();
				$this->session->set_flashdata('success', 'Nilai sudah diperbarui');
			}
			$this->db->trans_complete();

			redirect("dosen_mahasiswa/detail/".$this->input->post('nim', TRUE)."/".$this->input->post('kd_sub_praktikum', TRUE)."/".$this->input->post('id_konf', TRUE)."/".$this->input->post('kd_daftar_praktikum', TRUE),'refresh');
		}else{
			echo validation_errors();
		}
	}

	
    /*
     * Listing of mahasiswa
     */
    function index()
    {
        $data['mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi_dosen();

        $data['_view'] = 'dosen_mahasiswa/index';
		$data['judulform'] = 'MAHASISWA';
        $this->load->view('layouts/main_dosen',$data);
    }
	
	/*
     * Listing of nilai mahasiswa
     */
    function nilai($nim=null)
    {
        if($nim<>''){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				$this->load->model('Dosen_model');
				$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
				
				//get nilai 
				$data['all_nilai'] = $this->Nilai_model->get_nilai_praktek_dosen($nim);

				$data['_view'] = 'dosen_mahasiswa/nilai';
				$data['judulform'] = "Nilai Praktek";
				$this->load->view('layouts/main_dosen',$data);
			}else{
				redirect("dosen_mahasiswa","refresh");
			}	
		}else{
			redirect("dosen_mahasiswa","refresh");
		}
    }
	
	/*
     * Listing of detail nilai mahasiswa
     */
	function detail($nim=null, $subpraktikum=null, $id_konf=null, $kd_daftar_praktikum=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')and($kd_daftar_praktikum<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->db->query("select e.nama_praktikum, d.nama_sub_praktikum, h.nik_pasien, h.nama_pasien, h.tanggal_lahir_pasien, h.jk_pasien, g.nim, g.nama_mahasiswa, a.tanggal_praktek, i.kode_dosen, i.nama_dosen, j.diagnosa 
				
										from tbl_nilai_praktek a
											join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
											join tbl_aspek c on b.kd_aspek = c.id_aspek
											join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
											join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
											join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
											join tbl_mahasiswa g on a.nim=g.nim
											join tbl_pasien h on a.nik=h.nik_pasien
											join tbl_dosen i on a.kode_dosen=i.kode_dosen
											left join tbl_diagnosa j on j.id_sub_praktikum=c.kd_sub_praktikum and j.nik_pasien=a.nik and j.nim=a.nim and a.kd_daftar_praktikum=j.kd_daftar_praktikum
											where a.nim=? and d.id_sub_praktikum=? and f.id_konf=? and a.kd_daftar_praktikum=?",array($nim,$subpraktikum,$id_konf,$kd_daftar_praktikum))->row_array();
				
				//get detail nilai 
				$data['detail_nilai'] = $this->db->query("select * from tbl_nilai_praktek a
				join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
				join tbl_aspek c on b.kd_aspek = c.id_aspek
				join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
				join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
				join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
				join tbl_mahasiswa g on a.nim=g.nim
				where a.nim=? and d.id_sub_praktikum=? and f.id_konf=? and a.kd_daftar_praktikum=?",array($nim,$subpraktikum,$id_konf,$kd_daftar_praktikum))->result_array();

				$data['qnim'] = $nim;
				$data['qsubpraktikum'] = $subpraktikum;
				$data['qid_konf'] = $id_konf;
				$data['qkd_daftar_praktikum'] = $kd_daftar_praktikum;

				$data['_view'] = 'dosen_mahasiswa/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('layouts/main_dosen',$data);
			}else{
				redirect("mahasiswa","refresh");
			}	
		}else{
			redirect("mahasiswa","refresh");
		}
    }
	
	/*
     * Listing of print nilai mahasiswa
     */
	function nilai_mahasiswa_cetak($nim=null, $id_konf=null, $subpraktikum=null, $id_daftar_praktikum=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')and($id_daftar_praktikum<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->db->query("select e.nama_praktikum, d.nama_sub_praktikum, h.nik_pasien, h.nama_pasien, h.tanggal_lahir_pasien, h.jk_pasien, g.nim, g.nama_mahasiswa, a.tanggal_praktek, i.kode_dosen, i.nama_dosen, j.diagnosa 
				
										from tbl_nilai_praktek a
											join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
											join tbl_aspek c on b.kd_aspek = c.id_aspek
											join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
											join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
											join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
											join tbl_mahasiswa g on a.nim=g.nim
											join tbl_pasien h on a.nik=h.nik_pasien
											join tbl_dosen i on a.kode_dosen=i.kode_dosen
											left join tbl_diagnosa j on j.id_sub_praktikum=c.kd_sub_praktikum and j.nik_pasien=a.nik and j.nim=a.nim and a.kd_daftar_praktikum=j.kd_daftar_praktikum
											where a.nim=? and d.id_sub_praktikum=? and f.id_konf=? and a.kd_daftar_praktikum=?",array($nim,$subpraktikum,$id_konf,$id_daftar_praktikum))->row_array();
				
				//get detail nilai 
				$data['detail_nilai'] = $this->db->query("select * from tbl_nilai_praktek a
				join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
				join tbl_aspek c on b.kd_aspek = c.id_aspek
				join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
				join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
				join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
				join tbl_mahasiswa g on a.nim=g.nim
				where a.nim=? and d.id_sub_praktikum=? and f.id_konf=? and a.kd_daftar_praktikum=?",array($nim,$subpraktikum,$id_konf,$id_daftar_praktikum))->result_array();

				//$data['_view'] = 'nilai/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('dosen_mahasiswa/nilai_mahasiswa_print',$data);
			}else{
				redirect("dosen_mahasiswa/nilai_mahasiswa","refresh");
			}	
		}else{
			redirect("dosen_mahasiswa/nilai_mahasiswa","refresh");
		}
    }
    
}
