<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Konfigurasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login","refresh");
		}
        $this->load->model('Konfigurasi_model');
    } 

    /*
     * Listing of konfigurasi
     */
    function index()
    {
        $data['konfigurasi'] = $this->Konfigurasi_model->get_all_konfigurasi();

        $data['_view'] = 'konfigurasi/index';
		$data['judulform'] = 'KONFIGURASI';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new konfigurasi
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('thn_akademik','Thn Akademik','required');
		$this->form_validation->set_rules('kd_semester','Kd Semester','required');
		$this->form_validation->set_rules('status','Status','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'status' => $this->input->post('status'),
				'thn_akademik' => $this->input->post('thn_akademik'),
				'kd_semester' => $this->input->post('kd_semester'),
				'diinput_oleh' => $_SESSION['username_admin'],
            );
            
            $konfigurasi_id = $this->Konfigurasi_model->add_konfigurasi($params);
            redirect('konfigurasi/index');
        }
        else
        {            
            $data['_view'] = 'konfigurasi/add';
			$data['judulform'] = 'KONFIGURASI';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a konfigurasi
     */
    function edit($id_konf)
    {   
        // check if the konfigurasi exists before trying to edit it
        $data['konfigurasi'] = $this->Konfigurasi_model->get_konfigurasi($id_konf);
        
        if(isset($data['konfigurasi']['id_konf']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('thn_akademik','Thn Akademik','required');
			$this->form_validation->set_rules('kd_semester','Kd Semester','required');
			$this->form_validation->set_rules('status','Status','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'thn_akademik' => $this->input->post('thn_akademik'),
					'kd_semester' => $this->input->post('kd_semester'),
					'diupdate_oleh' => $_SESSION['username_admin'],
                );

                $this->Konfigurasi_model->update_konfigurasi($id_konf,$params);            
                redirect('konfigurasi/index');
            }
            else
            {
                $data['_view'] = 'konfigurasi/edit';
				
				$data['judulform'] = 'KONFIGURASI';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The konfigurasi you are trying to edit does not exist.');
    } 

    /*
     * Deleting konfigurasi
     */
    function remove($id_konf)
    {
        $konfigurasi = $this->Konfigurasi_model->get_konfigurasi($id_konf);

        // check if the konfigurasi exists before trying to delete it
        if(isset($konfigurasi['id_konf']))
        {
            $this->Konfigurasi_model->delete_konfigurasi($id_konf);
            redirect('konfigurasi/index');
        }
        else
            show_error('The konfigurasi you are trying to delete does not exist.');
    }
    
}
