<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_login');
    } 

    /*
     * Listing of tbl_admin
     */
    function index()
    {
        //$this->load->view('welcome');
		//session_destroy();
		
		// captcha
		$vals = array(
				'img_path'      => './captcha/',
				'img_url'       => 'http://erkmgigi.test:8080/captcha/',
				'pool'          => '0123456789',
				'word_length'   => 6,
		);

		$cap = create_captcha($vals);
		$data = array(
				'captcha_time'  => $cap['time'],
				'ip_address'    => $this->input->ip_address(),
				'word'          => $cap['word']
		);

		$query = $this->db->insert_string('captcha', $data);
		$this->db->query($query);

		$data['captchaImage'] = $cap['image'];
		
		$this->load->view('login/login', $data);
    }
	
	function cari(){
		$this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required');
		$this->form_validation->set_rules('username','Username','required');
		$this->form_validation->set_rules('captcha','Captcha','required');
		
		if($this->form_validation->run()){	
			// capthca
			// First, delete old captchas
			$expiration = time() - 7200; // Two hour limit
			$this->db->where('captcha_time < ', $expiration)
					->delete('captcha');

			// Then see if a captcha exists:
			$sql = 'SELECT COUNT(*) AS count FROM captcha WHERE word = ? AND ip_address = ? AND captcha_time > ?';
			$binds = array($this->security->xss_clean($this->input->post('captcha', TRUE)), $this->input->ip_address(), $expiration);
			$query = $this->db->query($sql, $binds);
			$row = $query->row();
			
			

			if ($row->count == 0)
			{
					//echo 'You must submit the word that appears in the image.';
					$this->session->set_flashdata("error","Angka yang dimasukkan salah!");
					redirect("login","refresh");
			}else{
				
			
			// akhir captcha
		
		
				$username	= $this->security->xss_clean($this->input->post('username', TRUE));
				$password 	= $this->security->xss_clean($this->input->post('password', TRUE));
				$hasil 		= $this->M_login->loginmahasiswa($username, $password);
				
				if (count($hasil->result_array())>0){
					foreach($hasil->result() as $items){
						$nim 		= $items->nim;
						$nama 		= $items->nama_mahasiswa;
					}
					
					$this->session->set_userdata('nim_mhs', $nim);
					$this->session->set_userdata('nama_mhs', $nama);
					
					
					//get konfig
					$this->load->model('M_konfigurasi_model');
					$tasmt 		= $this->M_konfigurasi_model->get_tbl_konfigurasi_aktif();
					
						foreach($tasmt as $data){
							$thn_akademik 		= $data['thn_akademik'];
							$kd_semester 		= $data['kd_semester'];
							$id_konf 			= $data['id_konf'];
						}
					
					
						$this->session->set_userdata('thn_akademik', $thn_akademik);
						$this->session->set_userdata('kd_semester', $kd_semester);
						$this->session->set_userdata('id_konf', $id_konf);
					
					redirect("ringkasan_nilai_mahasiswa","refresh");
				}else{
					
					$hasildosen 		= $this->M_login->logindosen($username, $password);
				
					if (count($hasildosen->result_array())>0){
						foreach($hasildosen->result() as $items){
							$kode_dosen = $items->kode_dosen;
							$nama_dosen	= $items->nama_dosen;
							$level_dosen = $items->level;
						}
						
						$this->session->set_userdata('kode_dosen', $kode_dosen);
						$this->session->set_userdata('nama_dosen', $nama_dosen);
						$this->session->set_userdata('level_dosen', $level_dosen);
						
						//get konfig
						$this->load->model('M_konfigurasi_model');
						$tasmt 		= $this->M_konfigurasi_model->get_tbl_konfigurasi_aktif();
						
							foreach($tasmt as $data){
								$thn_akademik 		= $data['thn_akademik'];
								$kd_semester 		= $data['kd_semester'];
								$id_konf 			= $data['id_konf'];
							}
						
						
							$this->session->set_userdata('thn_akademik', $thn_akademik);
							$this->session->set_userdata('kd_semester', $kd_semester);
							$this->session->set_userdata('id_konf', $id_konf);
						
						redirect("dosen_mahasiswa/input_nilai_mahasiswa","refresh");
					}else{
						
						$hasil 		= $this->M_login->loginadmin($username, $password);
						
						if (count($hasil->result_array())>0){
							foreach($hasil->result() as $items){
								$username 	= $items->username;
								$level 		= $items->level;
							}
							
							//$this->session->set_userdata('username_admin', $username);
							//$this->session->set_userdata('level_admin', $level);
							
							$user_sign = array(
								'username_admin'   => $username,
								'level_admin'      => $level,
								'logged_in'     => TRUE
							);
							
							$this->session->set_userdata($user_sign);
							
							var_dump($_SESSION);
							redirect("pendaftaran_praktikum/add","refresh");
						}else{
							$this->session->set_flashdata("error","Username atau password salah!");
							redirect("login","refresh");
						}
					}
				}
			}
		}else{
			$this->session->set_flashdata("error","Username atau password salah!");
			
			redirect("login","refresh");
		}
		
	}
}
