<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pasien extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login","refresh");
		}
        $this->load->model('Pasien_model');
    } 

    /*
     * Listing of pasien
     */
    function index()
    {
        $data['pasien'] = $this->Pasien_model->get_all_pasien();

        $data['_view'] = 'pasien/index';
		$data['judulform'] = 'PASIEN';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pasien
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nik_pasien','Nik Pasien','required');
		$this->form_validation->set_rules('nama_pasien','Nama Pasien','required');
		$this->form_validation->set_rules('jk_pasien','Jk Pasien','required');
		$this->form_validation->set_rules('tanggal_lahir_pasien','Tanggal Lahir Pasien','required');
		
		if($this->form_validation->run())     
        {
			$ada = $this->db->query("select * from tbl_pasien where nik_pasien=?",array($this->input->post('nik_pasien')))->num_rows();
			if($ada>0){
				$data['error'] = $this->session->set_flashdata('error', 'NIK pasien sudah terdaftar. Mohon periksa kembali NIK pasien Anda. Terima kasih');
			}else{
				$params = array(
					'jk_pasien' => $this->input->post('jk_pasien'),
					'nik_pasien' => $this->input->post('nik_pasien'),
					'nama_pasien' => $this->input->post('nama_pasien'),
					'tanggal_lahir_pasien' => $this->input->post('tanggal_lahir_pasien'),
					'hp_pasien' => $this->input->post('hp_pasien'),
					'diinput_oleh' => $_SESSION['username_admin'],
					//'diupdate_oleh' => $this->input->post('diupdate_oleh'),
					'alamat_pasien' => $this->input->post('alamat_pasien'),
				);
				
				$pasien_id = $this->Pasien_model->add_pasien($params);
				
				$data['success'] = $this->session->set_flashdata('success', 'Pendaftaran pasien berhasil. Terima kasih');
			}
            //redirect('pasien/index');
			$data['_view'] = 'pasien/add';
			$data['judulform'] = 'PASIEN';
            $this->load->view('layouts/main',$data);
        }
        else
        {            
            $data['_view'] = 'pasien/add';
			$data['judulform'] = 'PASIEN';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pasien
     */
    function edit($id_pasien)
    {   
        // check if the pasien exists before trying to edit it
        $data['pasien'] = $this->Pasien_model->get_pasien($id_pasien);
        
        if(isset($data['pasien']['id_pasien']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nik_pasien','Nik Pasien','required');
			$this->form_validation->set_rules('nama_pasien','Nama Pasien','required');
			$this->form_validation->set_rules('jk_pasien','Jk Pasien','required');
			$this->form_validation->set_rules('tanggal_lahir_pasien','Tanggal Lahir Pasien','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'jk_pasien' => $this->input->post('jk_pasien'),
					'nik_pasien' => $this->input->post('nik_pasien'),
					'nama_pasien' => $this->input->post('nama_pasien'),
					'tanggal_lahir_pasien' => $this->input->post('tanggal_lahir_pasien'),
					'hp_pasien' => $this->input->post('hp_pasien'),
					//'diinput_oleh' => $this->input->post('diinput_oleh'),
					'diupdate_oleh' => $_SESSION['username_admin'],
					'alamat_pasien' => $this->input->post('alamat_pasien'),
                );

                $this->Pasien_model->update_pasien($id_pasien,$params);            
                $data['success'] = $this->session->set_flashdata('success', 'Perubahan data pasien berhasil. Terima kasih');
				
				//redirect('pasien/index');
				$data['_view'] = 'pasien/edit';
				$data['judulform'] = 'PASIEN';
                $this->load->view('layouts/main',$data);
            }
            else
            {
                $data['_view'] = 'pasien/edit';
				$data['judulform'] = 'PASIEN';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pasien you are trying to edit does not exist.');
    } 

    /*
     * Deleting pasien
     */
    function remove($id_pasien)
    {
        $pasien = $this->Pasien_model->get_pasien($id_pasien);

        // check if the pasien exists before trying to delete it
        if(isset($pasien['id_pasien']))
        {
            $this->Pasien_model->delete_pasien($id_pasien);
            redirect('pasien/index');
        }
        else
            show_error('The pasien you are trying to delete does not exist.');
    }

    function get_data_pasien()
	{
        $this->load->model('Pasien_db_model');
		$list = $this->Pasien_db_model->get_datatables();
		$data = array();
		$no = $_POST['start'];
		foreach ($list as $field) {
			$no++;
			$row = array();
            $row[] = $no;
            
			$row[] = $field->nik_pasien;
			$row[] = $field->nama_pasien;
            $row[] = $field->jk_pasien;
            $row[] = $field->tanggal_lahir_pasien;
            $row[] = $field->hp_pasien;
            $row[] = $field->alamat_pasien;
            $row[] = '<a href="'.base_url("pasien/edit/$field->id_pasien").'" class="btn btn-info btn-xs">Edit</a> / <a href="'.base_url("pasien/delete/$field->id_pasien").'" class="btn btn-danger btn-xs">Delete</a>';

			$data[] = $row;
		}

		$output = array(
			"draw" => $_POST['draw'],
			"recordsTotal" => $this->Pasien_db_model->count_all(),
			"recordsFiltered" => $this->Pasien_db_model->count_filtered(),
			"data" => $data,
		);
		//output dalam format JSON
		echo json_encode($output);
	}
    
}
