<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pasien_mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['nim_mhs']) ? $_SESSION['nim_mhs']:'';
		if($session==""){
			redirect("login","refresh");
		}
        $this->load->model('Pasien_model');
    } 

    /*
     * Listing of pasien
     */
    function index()
    {
        $data['pasien'] = $this->Pasien_model->get_all_pasien_mahasiswa();

        $data['_view'] = 'pasien_mahasiswa/index';
		$data['judulform'] = 'PASIEN';
        $this->load->view('layouts/main_mahasiswa',$data);
    }

    /*
     * Adding a new pasien
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nik_pasien','Nik Pasien','required');
		$this->form_validation->set_rules('nama_pasien','Nama Pasien','required');
		$this->form_validation->set_rules('jk_pasien','Jk Pasien','required');
		$this->form_validation->set_rules('tanggal_lahir_pasien','Tanggal Lahir Pasien','required');
		
		if($this->form_validation->run())     
        {   
            $ada = $this->db->query("select * from tbl_pasien where nik_pasien=?",array($this->input->post('nik_pasien')))->num_rows();
			if($ada > 0){
				$data['error'] = $this->session->set_flashdata('error', 'NIK pasien sudah terdaftar. Mohon periksa kembali NIK pasien Anda. Terima kasih');
			}else{
				$params = array(
					'jk_pasien' => $this->input->post('jk_pasien'),
					'nik_pasien' => $this->input->post('nik_pasien'),
					'nama_pasien' => $this->input->post('nama_pasien'),
					'tanggal_lahir_pasien' => $this->input->post('tanggal_lahir_pasien'),
					'hp_pasien' => $this->input->post('hp_pasien'),
					'diinput_oleh' => $_SESSION['nim_mhs'],
					//'diupdate_oleh' => $this->input->post('diupdate_oleh'),
					'alamat_pasien' => $this->input->post('alamat_pasien'),
				);
				
				$pasien_id = $this->Pasien_model->add_pasien($params);
				
				$data['success'] = $this->session->set_flashdata('success', 'Pendaftaran pasien berhasil. Terima kasih');
			}
            //redirect('pasien_mahasiswa/index');
			$data['_view'] = 'pasien_mahasiswa/add';
			$data['judulform'] = 'PASIEN';
            $this->load->view('layouts/main_mahasiswa',$data);
        }
        else
        {            
            $data['_view'] = 'pasien_mahasiswa/add';
			$data['judulform'] = 'PASIEN';
            $this->load->view('layouts/main_mahasiswa',$data);
        }
    }  

    /*
     * Editing a pasien
     */
    function edit($id_pasien)
    {   
        // check if the pasien exists before trying to edit it
        // $data['pasien'] = $this->Pasien_model->get_pasien_mahasiswa($id_pasien);
        $data['pasien'] = $this->Pasien_model->get_pasienmahasiswa($id_pasien);
        
        if(isset($data['pasien']['id_pasien']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nik_pasien','Nik Pasien','required');
			$this->form_validation->set_rules('nama_pasien','Nama Pasien','required');
			$this->form_validation->set_rules('jk_pasien','Jk Pasien','required');
			$this->form_validation->set_rules('tanggal_lahir_pasien','Tanggal Lahir Pasien','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'jk_pasien' => $this->input->post('jk_pasien'),
					'nik_pasien' => $this->input->post('nik_pasien'),
					'nama_pasien' => $this->input->post('nama_pasien'),
					'tanggal_lahir_pasien' => $this->input->post('tanggal_lahir_pasien'),
					'hp_pasien' => $this->input->post('hp_pasien'),
					//'diinput_oleh' => $this->input->post('diinput_oleh'),
					'diupdate_oleh' => $_SESSION['nim_mhs'],
					'alamat_pasien' => $this->input->post('alamat_pasien'),
                );

                $this->Pasien_model->update_pasien($id_pasien,$params);            
				$data['success'] = $this->session->set_flashdata('success', 'Perubahan data pasien berhasil. Terima kasih');
                
				//redirect('pasien_mahasiswa/index');
				$data['_view'] = 'pasien_mahasiswa/edit';
				$data['judulform'] = 'PASIEN';
                $this->load->view('layouts/main_mahasiswa',$data);
            }
            else
            {
                $data['_view'] = 'pasien_mahasiswa/edit';
				$data['judulform'] = 'PASIEN';
                $this->load->view('layouts/main_mahasiswa',$data);
            }
        }
        else
            show_error('The pasien you are trying to edit does not exist.');
    } 

    /*
     * View a pasien
     */
    function view($id_pasien)
    {   
        // check if the pasien exists before trying to edit it
        // $data['pasien'] = $this->Pasien_model->get_pasien_mahasiswa($id_pasien);
        $data['pasien'] = $this->Pasien_model->get_pasienmahasiswa($id_pasien);
        
        if(isset($data['pasien']['id_pasien']))
        {

            $data['listing_mahasiswa'] = $this->db->query("select a.id_daftar_praktikum, a.tanggal_praktek, a.nim, a.kode_dosen, a.kd_sub_praktikum, a.kd_konfigurasi, a.semester, g.nilai_rata,
			b.nama_mahasiswa, c.nama_dosen, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester, a.diagnosa_pasien, a.diagnosa_odontogram, p.nik_pasien, p.nama_pasien
                        from tbl_praktikum_mahasiswa a 
                        join tbl_pasien p on a.nik = p.nik_pasien
						join tbl_mahasiswa b on a.nim=b.nim
						join tbl_dosen c on a.kode_dosen=c.kode_dosen
						join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
						join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
						join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf 
						join (select nim as nim_r, kd_konfigurasi as kd_konfigurasi_r, kd_sub_praktikum as kd_sub_praktikum_r, AVG(nilai) as nilai_rata 
							  from tbl_praktikum_mahasiswa group by nim, kd_konfigurasi, kd_sub_praktikum) g on a.nim=g.nim_r and a.kd_konfigurasi=g.kd_konfigurasi_r and a.kd_sub_praktikum=g.kd_sub_praktikum_r
            where p.id_pasien=? and a.nim=?
            group by a.nim, a.kd_konfigurasi, a.kd_sub_praktikum, a.kode_dosen", array($id_pasien, $_SESSION['nim_mhs']))->result_array();

            $data['_view'] = 'pasien_mahasiswa/view';
            $data['judulform'] = 'PASIEN';
            $this->load->view('layouts/main_mahasiswa',$data);
        
        }
        else
            show_error('The pasien you are trying to edit does not exist.');
    } 

    /*
     * Deleting pasien
     */
    /*function remove($id_pasien)
    {
        $pasien = $this->Pasien_model->get_pasien($id_pasien);

        // check if the pasien exists before trying to delete it
        if(isset($pasien['id_pasien']))
        {
            $this->Pasien_model->delete_pasien_mahasiswa($id_pasien);
            redirect('pasien_mahasiswa/index');
        }
        else
            show_error('The pasien you are trying to delete does not exist.');
    }*/
    
}
