<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pendaftaran_praktikum extends CI_Controller {
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			$this->session->set_flashdata('info', '<div class="alert alert-danger">Session habis.</div>');
			//redirect("login","refresh");
		}
		//var_dump($_SESSION);
	} 
	
	/*
     * Adding a new nilai_praktek
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_konf','Thn Akademik & Semester','required');
		$this->form_validation->set_rules('nim','Nama Mahasiswa','required');
		$this->form_validation->set_rules('semester','Semester','required');
		$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		$this->form_validation->set_rules('nik','Nama Pasien','required');
		$this->form_validation->set_rules('kode_dosen','Dosen Pembimbing','required');
		$this->form_validation->set_rules('tanggal_praktek','Tanggal Praktek','required');
		// $this->form_validation->set_rules('diagnosa_odontogram','Diagnosa Odontogram','required');
		// $this->form_validation->set_rules('diagnosa_pasien','Diagnosa Pasien','required');
		
		if($this->form_validation->run())     
        {   	
			// uploads diagnosa odontogram
			$config['upload_path']          = './diagnosa/';
            $config['allowed_types']        = 'jpg|png';
            $config['max_size']             = 250000;
            $config['remove_spaces']        = TRUE;
            
            $new_name = time().$_FILES['diagnosa_odontogram']['name'];
            $config['file_name'] = $new_name;
            $config['file_name'] = str_replace(' ', '_', $config['file_name']);

            $this->load->library('upload', $config);

            if ($this->upload->do_upload('diagnosa_odontogram'))
            {		
				$params = array(
					'kd_konfigurasi' => $this->input->post('id_konf', TRUE),
					'nim' => $this->input->post('nim', TRUE),
					'semester' => $this->input->post('semester', TRUE),
					'kd_sub_praktikum' => $this->input->post('kd_sub_praktikum', TRUE),
					'nik' => $this->input->post('nik', TRUE),
					'kode_dosen' => $this->input->post('kode_dosen', TRUE),
					'tanggal_praktek' => $this->input->post('tanggal_praktek', TRUE),
					'diagnosa_pasien' => $this->input->post('diagnosa_pasien', TRUE),
					'diagnosa_odontogram' => $config['file_name'],
					'tanggal_input' => date('Y-m-d'),
					'diinput_oleh' => $_SESSION['username_admin']
				);
				
				$this->db->insert('tbl_praktikum_mahasiswa', $params);
				$this->session->set_flashdata('success', 'Daftar praktikum berhasil disimpan.');

			} else {
				// $this->session->set_flashdata('error', 'File gagal diupload. <br>'.$this->upload->display_errors());
				$params = array(
					'kd_konfigurasi' => $this->input->post('id_konf', TRUE),
					'nim' => $this->input->post('nim', TRUE),
					'semester' => $this->input->post('semester', TRUE),
					'kd_sub_praktikum' => $this->input->post('kd_sub_praktikum', TRUE),
					'nik' => $this->input->post('nik', TRUE),
					'kode_dosen' => $this->input->post('kode_dosen', TRUE),
					'tanggal_praktek' => $this->input->post('tanggal_praktek', TRUE),
					'diagnosa_pasien' => $this->input->post('diagnosa_pasien', TRUE),
					'tanggal_input' => date('Y-m-d'),
					'diinput_oleh' => $_SESSION['username_admin']
				);
				
				$this->db->insert('tbl_praktikum_mahasiswa', $params);
				$this->session->set_flashdata('success', 'Daftar praktikum berhasil disimpan dengan tidak melampirkan file diagnosa odontogram.');
			}

			$this->load->model('Dosen_model');
			$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
			
			$this->load->model('M_konfigurasi_model');
			$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
			
			$this->load->model('Mahasiswa_model');
			$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi();

			$this->load->model('Sub_praktikum_model');
			$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();

			$this->load->model('Pasien_model');
			$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

			// tabel daftar praktikum
			// $data['daftar_praktikum'] = $this->db->query("select a.* , b.nama_mahasiswa, c.nama_dosen, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester
			// from tbl_praktikum_mahasiswa a 
			// join tbl_mahasiswa b on a.nim=b.nim
			// join tbl_dosen c on a.kode_dosen=c.kode_dosen
			// join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
			// join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
			// join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf where a.tanggal_praktek=?", array($this->input->post('tanggal_praktek', TRUE)))->result_array();
			
			$data['_cari'] = false;
			
			$data['_view'] = 'pendaftaran_praktikum/add';
			$data['judulform'] = 'PENDAFTARAN PRAKTIKUM';
			$this->load->view('layouts/main',$data);
		}
        else
        {
			$this->load->model('Dosen_model');
			$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
			
			$this->load->model('M_konfigurasi_model');
			$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
			
			$this->load->model('Mahasiswa_model');
			$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi();

			$this->load->model('Sub_praktikum_model');
			$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();

			$this->load->model('Pasien_model');
			$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

			if($this->input->post('tanggal_praktek_cari')){
				$tanggal = $this->input->post('tanggal_praktek_cari');
			}else{
				$tanggal = date('Y-m-d');
			}

			$data['_cari'] = true;

			// tabel daftar praktikum
			// $data['daftar_praktikum'] = $this->db->query("select a.* , b.nama_mahasiswa, c.nama_dosen, d.nama_sub_praktikum, e.nama_praktikum, f.thn_akademik, f.kd_semester
			// from tbl_praktikum_mahasiswa a 
			// join tbl_mahasiswa b on a.nim=b.nim
			// join tbl_dosen c on a.kode_dosen=c.kode_dosen
			// join tbl_sub_praktikum d on a.kd_sub_praktikum=d.id_sub_praktikum
			// join tbl_praktikum e on d.kd_praktikum=e.id_praktikum
			// join tbl_konfigurasi f on a.kd_konfigurasi=f.id_konf where a.tanggal_praktek=?", array($tanggal))->result_array(); 
            
            $data['_view'] = 'pendaftaran_praktikum/add';
			$data['judulform'] = 'PENDAFTARAN PRAKTIKUM';
            $this->load->view('layouts/main',$data);
        }
    }

	function remove($id_daftar_praktikum)
    {
        $daftar_praktikum = $this->db->query("select * from tbl_praktikum_mahasiswa where id_daftar_praktikum=?", array($id_daftar_praktikum))->row_array();

        // check if the pasien exists before trying to delete it
        if(isset($daftar_praktikum['id_daftar_praktikum']))
        {
			$this->db->delete('tbl_praktikum_mahasiswa',array('id_daftar_praktikum'=>$id_daftar_praktikum));
			$this->session->set_flashdata('error', 'Daftar praktikum sudah dihapus.');
            redirect('pendaftaran_praktikum/add');
        }
        else
            show_error('The pasien you are trying to delete does not exist.');
	}
	
	function get_pendaftaran_praktikum()
	{
        $this->load->model('Praktikum_db_model');
		$list = $this->Praktikum_db_model->get_datatables();
		$data = array();
		$no = $_POST['start'];
		foreach ($list as $field) {
			$no++;
			$row = array();
            $row[] = $no;
			
			$row[] = $field->tanggal_praktek;
			$row[] = $field->thn_akademik."-".$field->kd_semester;
            $row[] = $field->semester;
            $row[] = $field->nim;
			$row[] = $field->nama_mahasiswa;
			$row[] = $field->nama_praktikum;
			$row[] = $field->nama_sub_praktikum;
			$row[] = $field->nama_dosen;
			$row[] = ($field->status == "N" ? "<span class='alert alert-danger' style='padding:4px'>Belum</span>" : "<span class='alert alert-success' style='padding:4px'>Sudah</span>");
            $row[] = '<a href="'.base_url("pendaftaran_praktikum/remove/$field->id_daftar_praktikum").'" class="btn btn-danger btn-xs">Delete</a>';

			$data[] = $row;
		}

		$output = array(
			"draw" => $_POST['draw'],
			"recordsTotal" => $this->Praktikum_db_model->count_all(),
			"recordsFiltered" => $this->Praktikum_db_model->count_filtered(),
			"data" => $data,
		);
		//output dalam format JSON
		echo json_encode($output);
	}
}
