<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Praktikum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login","refresh");
		}
        $this->load->model('Praktikum_model');
    } 

    /*
     * Listing of praktikum
     */
    function index()
    {
        $data['praktikum'] = $this->Praktikum_model->get_all_praktikum();

        $data['_view'] = 'praktikum/index';
		$data['judulform'] = 'PRAKTIKUM';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new praktikum
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_praktikum','Nama Praktikum','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_praktikum' => $this->input->post('nama_praktikum'),
				'diinput_oleh' => $_SESSION['username_admin'],
            );
            
            $praktikum_id = $this->Praktikum_model->add_praktikum($params);
            redirect('praktikum/index');
        }
        else
        {            
            $data['_view'] = 'praktikum/add';
			$data['judulform'] = 'PRAKTIKUM';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a praktikum
     */
    function edit($id_praktikum)
    {   
        // check if the praktikum exists before trying to edit it
        $data['praktikum'] = $this->Praktikum_model->get_praktikum($id_praktikum);
        
        if(isset($data['praktikum']['id_praktikum']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_praktikum','Nama Praktikum','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_praktikum' => $this->input->post('nama_praktikum'),
					'diupdate_oleh' => $_SESSION['username_admin'],
                );

                $this->Praktikum_model->update_praktikum($id_praktikum,$params);            
                redirect('praktikum/index');
            }
            else
            {
                $data['_view'] = 'praktikum/edit';
				$data['judulform'] = 'PRAKTIKUM';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The praktikum you are trying to edit does not exist.');
    } 

    /*
     * Deleting praktikum
     */
    function remove($id_praktikum)
    {
        $praktikum = $this->Praktikum_model->get_praktikum($id_praktikum);

        // check if the praktikum exists before trying to delete it
        if(isset($praktikum['id_praktikum']))
        {
            $this->Praktikum_model->delete_praktikum($id_praktikum);
            redirect('praktikum/index');
        }
        else
            show_error('The praktikum you are trying to delete does not exist.');
    }
    
}
