<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Aspek_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aspek by id_aspek
     */
    function get_aspek($id_aspek)
    {
        return $this->db->get_where('tbl_aspek',array('id_aspek'=>$id_aspek))->row_array();
    }
    
    /*
     * Get all aspek
     */
    function get_all_aspek()
    {
		$this->db->select('tbl_aspek.*, tbl_sub_praktikum.id_sub_praktikum, tbl_sub_praktikum.nama_sub_praktikum, tbl_praktikum.id_praktikum, tbl_praktikum.nama_praktikum');
		$this->db->from('tbl_aspek');
		$this->db->join('tbl_sub_praktikum', 'tbl_aspek.kd_sub_praktikum = tbl_sub_praktikum.id_sub_praktikum');
		$this->db->join('tbl_praktikum', 'tbl_praktikum.id_praktikum = tbl_sub_praktikum.kd_praktikum');
		$this->db->order_by('tbl_praktikum.nama_praktikum','asc');
		$this->db->order_by('tbl_sub_praktikum.nama_sub_praktikum','asc');
		$this->db->order_by('tbl_aspek.id_aspek','asc');
        return $this->db->get()->result_array();
    }
    
    /*
     * function to add new aspek
     */
    function add_aspek($params)
    {
        $this->db->insert('tbl_aspek',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update aspek
     */
    function update_aspek($id_aspek,$params)
    {
        $this->db->where('id_aspek',$id_aspek);
        $response = $this->db->update('tbl_aspek',$params);
        if($response)
        {
            return "aspek updated successfully";
        }
        else
        {
            return "Error occuring while updating aspek";
        }
    }
    
    /*
     * function to delete aspek
     */
    function delete_aspek($id_aspek)
    {
        $response = $this->db->delete('tbl_aspek',array('id_aspek'=>$id_aspek));
        if($response)
        {
            return "aspek deleted successfully";
        }
        else
        {
            return "Error occuring while deleting aspek";
        }
    }
}
