<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Nilai_praktek_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get nilai_praktek by id_nilai_praktek
     */
    function get_nilai_praktek($id_nilai_praktek)
    {
        return $this->db->get_where('tbl_nilai_praktek',array('id_nilai_praktek'=>$id_nilai_praktek))->row_array();
    }
    
    /*
     * Get all nilai_praktek
     */
    function get_all_nilai_praktek()
    {
        //return $this->db->get('tbl_nilai_praktek')->result_array();
		return $this->db->query("select a.*, b.nama_mahasiswa, c.nama_pasien, d.nama_sub_aspek, e.nama_aspek, f.nama_sub_praktikum, g.nama_praktikum, i.thn_akademik, i.kd_semester from tbl_nilai_praktek a 
								join tbl_mahasiswa b on a.nim=b.nim
								join tbl_pasien c on a.nik=c.nik_pasien
								join tbl_sub_aspek d on a.kd_sub_aspek=d.id_sub_aspek
								join tbl_aspek e on d.kd_aspek=e.id_aspek
								join tbl_sub_praktikum f on e.kd_sub_praktikum=f.id_sub_praktikum
								join tbl_praktikum g on f.kd_praktikum=g.id_praktikum
								join tbl_konfigurasi i on a.kd_konfigurasi=i.id_konf
								")->result_array();
    }
	
	function get_all_nilai_praktek_cari($nim, $sub_praktikum)
    {
        //return $this->db->get('tbl_nilai_praktek')->result_array();
		return $this->db->query("select a.*, b.nama_mahasiswa, c.nama_pasien, d.nama_sub_aspek, e.nama_aspek, f.nama_sub_praktikum, g.nama_praktikum, i.thn_akademik, i.kd_semester from tbl_nilai_praktek a 
								join tbl_mahasiswa b on a.nim=b.nim
								join tbl_pasien c on a.nik=c.nik_pasien
								join tbl_sub_aspek d on a.kd_sub_aspek=d.id_sub_aspek
								join tbl_aspek e on d.kd_aspek=e.id_aspek
								join tbl_sub_praktikum f on e.kd_sub_praktikum=f.id_sub_praktikum
								join tbl_praktikum g on f.kd_praktikum=g.id_praktikum
								join tbl_konfigurasi i on a.kd_konfigurasi=i.id_konf
								where a.nim=? and e.kd_sub_praktikum=?
								", array($nim, $sub_praktikum))->result_array();
    }
    
    /*
     * function to add new nilai_praktek
     */
    function add_nilai_praktek($params)
    {
        $this->db->insert('tbl_nilai_praktek',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update nilai_praktek
     */
    function update_nilai_praktek($id_nilai_praktek,$params)
    {
        $this->db->where('id_nilai_praktek',$id_nilai_praktek);
        $response = $this->db->update('tbl_nilai_praktek',$params);
        if($response)
        {
            return "nilai_praktek updated successfully";
        }
        else
        {
            return "Error occuring while updating nilai_praktek";
        }
    }
    
    /*
     * function to delete nilai_praktek
     */
    function delete_nilai_praktek($id_nilai_praktek)
    {
        $response = $this->db->delete('tbl_nilai_praktek',array('id_nilai_praktek'=>$id_nilai_praktek));
        if($response)
        {
            return "nilai_praktek deleted successfully";
        }
        else
        {
            return "Error occuring while deleting nilai_praktek";
        }
    }
}
