<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Nilai_mahasiswa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
	/*
     * Get nilai_praktek by id_nilai_praktek
     */
    function get_nilai_praktek($nim)
    {
        return $this->db->query("select a.nim, f.thn_akademik, f.kd_semester, f.id_konf, e.nama_praktikum, d.id_sub_praktikum, d.nama_sub_praktikum, sum(a.angka_perolehan) as j_ap, sum(b.rentang_skor_akhir) as j_max_skor, sum(b.bobot) as j_bobot,
									sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) as skor,
									((sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) / sum(b.bobot)) * 100) as nilai
									from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
									where a.nim=? group by a.nim, d.id_sub_praktikum",array($nim))->result_array();
    }
	
	function get_list_praktek($nim)
	{
		return $this->db->query("select a.id_praktikum, a.nama_praktikum, b.id_sub_praktikum, b.nama_sub_praktikum, d.nim, e.thn_akademik, e.kd_semester, e.id_konf,e.nilai,  concat(substr(e.tanggal_praktek,9,2),'-',substr(e.tanggal_praktek,6,2),'-',substr(e.tanggal_praktek,1,4)) as tanggal_praktek
								from tbl_praktikum a 
								left join tbl_sub_praktikum b 
								on a.id_praktikum=b.kd_praktikum
								left join (select z.nim, x.kd_sub_praktikum from tbl_nilai_praktek z 
								join tbl_sub_aspek y on z.kd_sub_aspek=y.id_sub_aspek
								join tbl_aspek x on y.kd_aspek=x.id_aspek
								group by z.nim, x.kd_sub_praktikum) d on b.id_sub_praktikum=d.kd_sub_praktikum  
								left join (select a.tanggal_praktek, a.nim, f.thn_akademik, f.kd_semester, f.id_konf, e.nama_praktikum, d.id_sub_praktikum, d.nama_sub_praktikum, sum(a.angka_perolehan) as j_ap, sum(b.rentang_skor_akhir) as j_max_skor, sum(b.bobot) as j_bobot,
									sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) as skor,
									((sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) / sum(b.bobot)) * 100) as nilai
									from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim group by a.nim, d.id_sub_praktikum) e on d.nim=e.nim and b.id_sub_praktikum=e.id_sub_praktikum
									where d.nim = ? or d.nim is null", array($nim))->result_array();
	}
	
	/*
     * Get nilai_praktek by id_nilai_praktek
     */
    function get_info_mahasiswa_pasien($nim,$subpraktikum,$id_konf)
    {
        return $this->db->query("select e.nama_praktikum, d.nama_sub_praktikum, h.nik_pasien, h.nama_pasien, h.tanggal_lahir_pasien, h.jk_pasien, g.nim, g.nama_mahasiswa, a.tanggal_praktek, i.kode_dosen, i.nama_dosen 
		
								from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
                                    join tbl_pasien h on a.nik=h.nik_pasien
									join tbl_dosen i on a.kode_dosen=i.kode_dosen
									where a.nim=? and d.id_sub_praktikum=? and f.id_konf=?",array($nim,$subpraktikum,$id_konf))->row_array();
    }
	
	/*
     * Get nilai_praktek by id_nilai_praktek
     */
    function get_nilai_praktek_detail($nim,$subpraktikum,$id_konf)
    {
        return $this->db->query("select * from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
									where a.nim=? and d.id_sub_praktikum=? and f.id_konf=?",array($nim,$subpraktikum,$id_konf))->result_array();
    }
}
