<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Nilai_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
	/*
     * Get nilai_praktek by id_nilai_praktek
     */
    function get_nilai_praktek($nim)
    {
        return $this->db->query("select a.nim, f.thn_akademik, f.kd_semester, f.id_konf, e.nama_praktikum, d.id_sub_praktikum, d.nama_sub_praktikum, sum(a.angka_perolehan) as j_ap, sum(b.rentang_skor_akhir) as j_max_skor, sum(b.bobot) as j_bobot,
									sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) as skor,
									((sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) / sum(b.bobot)) * 100) as nilai
									from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
									where a.nim=? group by a.nim, d.id_sub_praktikum",array($nim))->result_array();
    }
	
	function get_nilai_praktek_dosen($nim)
    {
        if($_SESSION['level_dosen']==1){
		return $this->db->query("select a.nim, f.thn_akademik, f.kd_semester, f.id_konf, e.nama_praktikum, d.id_sub_praktikum, d.nama_sub_praktikum, sum(a.angka_perolehan) as j_ap, sum(b.rentang_skor_akhir) as j_max_skor, sum(b.bobot) as j_bobot,
									sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) as skor,
									((sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) / sum(b.bobot)) * 100) as nilai
									from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
									where a.nim=? and a.kode_dosen=?
									group by a.nim, d.id_sub_praktikum",array($nim, $_SESSION['kode_dosen']))->result_array();
		}else{
			return $this->db->query("select a.nim, f.thn_akademik, f.kd_semester, f.id_konf, e.nama_praktikum, d.id_sub_praktikum, d.nama_sub_praktikum, sum(a.angka_perolehan) as j_ap, sum(b.rentang_skor_akhir) as j_max_skor, sum(b.bobot) as j_bobot,
									sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) as skor,
									((sum((a.angka_perolehan/b.rentang_skor_akhir)*b.bobot) / sum(b.bobot)) * 100) as nilai
									from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
									where a.nim=? 
									group by a.nim, d.id_sub_praktikum",array($nim))->result_array();
		}
    }
	
	/*
     * Get nilai_praktek by id_nilai_praktek
     */
    function get_info_mahasiswa_pasien($nim,$subpraktikum,$id_konf)
    {
        return $this->db->query("select e.nama_praktikum, d.nama_sub_praktikum, h.nik_pasien, h.nama_pasien, h.tanggal_lahir_pasien, h.jk_pasien, g.nim, g.nama_mahasiswa, a.tanggal_praktek, i.kode_dosen, i.nama_dosen, j.diagnosa 
		
								from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
                                    join tbl_pasien h on a.nik=h.nik_pasien
									join tbl_dosen i on a.kode_dosen=i.kode_dosen
									left join tbl_diagnosa j on j.id_sub_praktikum=c.kd_sub_praktikum and j.nik_pasien=a.nik and j.nim=a.nim
									where a.nim=? and d.id_sub_praktikum=? and f.id_konf=?",array($nim,$subpraktikum,$id_konf))->row_array();
    }
	
	/*
     * Get nilai_praktek by id_nilai_praktek
     */
    function get_nilai_praktek_detail($nim,$subpraktikum,$id_konf)
    {
        return $this->db->query("select * from tbl_nilai_praktek a
									join tbl_sub_aspek b on a.kd_sub_aspek = b.id_sub_aspek
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									join tbl_konfigurasi f on a.kd_konfigurasi = f.id_konf
									join tbl_mahasiswa g on a.nim=g.nim
									where a.nim=? and d.id_sub_praktikum=? and f.id_konf=?",array($nim,$subpraktikum,$id_konf))->result_array();
    }
}
