<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pasien_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pasien by id_pasien
     */
    function get_pasien($id_pasien)
    {
        return $this->db->get_where('tbl_pasien',array('id_pasien'=>$id_pasien))->row_array();
    }
	
	 /*
     * Get pasien by id_pasien by mahasiswa
     */
    function get_pasien_mahasiswa($id_pasien)
    {
        return $this->db->get_where('tbl_pasien',array('id_pasien'=>$id_pasien, 'diinput_oleh'=>$_SESSION['nim_mhs']))->row_array();
    }
    
    /*
     * Get all pasien
     */
    function get_all_pasien()
    {
        return $this->db->get('tbl_pasien')->result_array();
    }
	
	/*
     * Get all pasien by mahasiswa
     */
    function get_all_pasien_mahasiswa()
    {
        //return $this->db->get('tbl_pasien')->result_array();
		return $this->db->query("select * from tbl_pasien where diinput_oleh=?", array($_SESSION['nim_mhs']))->result_array();
    }
    
    /*
     * function to add new pasien
     */
    function add_pasien($params)
    {
        $this->db->insert('tbl_pasien',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pasien
     */
    function update_pasien($id_pasien,$params)
    {
        $this->db->where('id_pasien',$id_pasien);
        $response = $this->db->update('tbl_pasien',$params);
        if($response)
        {
            return "pasien updated successfully";
        }
        else
        {
            return "Error occuring while updating pasien";
        }
    }
    
    /*
     * function to delete pasien
     */
    function delete_pasien($id_pasien)
    {
        $response = $this->db->delete('tbl_pasien',array('id_pasien'=>$id_pasien));
        if($response)
        {
            return "pasien deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pasien";
        }
    }
	
	 /*
     * function to delete pasien bt mahasiswa
     */
    function delete_pasien_mahasiswa($id_pasien)
    {
        $response = $this->db->delete('tbl_pasien',array('id_pasien'=>$id_pasien, 'diinput_oleh' =>$_SESSION['nim_mhs']));
        if($response)
        {
            return "pasien deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pasien";
        }
    }
}
