<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Sub_praktikum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sub_praktikum by id_sub_praktikum
     */
    function get_sub_praktikum($id_sub_praktikum)
    {
		return $this->db->get_where('tbl_sub_praktikum',array('id_sub_praktikum'=>$id_sub_praktikum))->row_array();
    }
    
    /*
     * Get all sub_praktikum
     */
    function get_all_sub_praktikum()
    {
        //return $this->db->get('tbl_sub_praktikum')->result_array();
		$this->db->select('tbl_sub_praktikum.*, tbl_praktikum.nama_praktikum');
		$this->db->from('tbl_sub_praktikum');
		$this->db->join('tbl_praktikum', 'tbl_sub_praktikum.kd_praktikum = tbl_praktikum.id_praktikum');
		return $this->db->get()->result_array();
    }
    
    /*
     * function to add new sub_praktikum
     */
    function add_sub_praktikum($params)
    {
        $this->db->insert('tbl_sub_praktikum',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sub_praktikum
     */
    function update_sub_praktikum($id_sub_praktikum,$params)
    {
        $this->db->where('id_sub_praktikum',$id_sub_praktikum);
        $response = $this->db->update('tbl_sub_praktikum',$params);
        if($response)
        {
            return "sub_praktikum updated successfully";
        }
        else
        {
            return "Error occuring while updating sub_praktikum";
        }
    }
    
    /*
     * function to delete sub_praktikum
     */
    function delete_sub_praktikum($id_sub_praktikum)
    {
        $response = $this->db->delete('tbl_sub_praktikum',array('id_sub_praktikum'=>$id_sub_praktikum));
        if($response)
        {
            return "sub_praktikum deleted successfully";
        }
        else
        {
            return "Error occuring while deleting sub_praktikum";
        }
    }
}
