<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Sub_aspek_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sub_aspek by id_sub_aspek
     */
    function get_sub_aspek($id_sub_aspek)
    {
        return $this->db->get_where('tbl_sub_aspek',array('id_sub_aspek'=>$id_sub_aspek))->row_array();
    }
    
    /*
     * Get all sub_aspek
     */
    function get_all_sub_aspek()
    {
        $this->db->select('tbl_sub_aspek.*, tbl_aspek.nama_aspek, tbl_sub_praktikum.id_sub_praktikum, tbl_sub_praktikum.nama_sub_praktikum, tbl_praktikum.id_praktikum, tbl_praktikum.nama_praktikum');
		$this->db->from('tbl_sub_aspek');
		$this->db->join('tbl_aspek', 'tbl_aspek.id_aspek = tbl_sub_aspek.kd_aspek');
		$this->db->join('tbl_sub_praktikum', 'tbl_aspek.kd_sub_praktikum = tbl_sub_praktikum.id_sub_praktikum');
		$this->db->join('tbl_praktikum', 'tbl_praktikum.id_praktikum = tbl_sub_praktikum.kd_praktikum');
        return $this->db->get()->result_array();
    }
	
	/*
     * Get all sub_aspek where sub_praktikum
     */
    function get_all_sub_aspek_sub_praktikum($sub_praktikum)
    {
        /*$this->db->select('tbl_sub_aspek.*, tbl_aspek.nama_aspek, tbl_sub_praktikum.id_sub_praktikum, tbl_sub_praktikum.nama_sub_praktikum, tbl_praktikum.id_praktikum, tbl_praktikum.nama_praktikum');
		$this->db->from('tbl_sub_aspek');
		$this->db->join('tbl_aspek', 'tbl_aspek.id_aspek = tbl_sub_aspek.kd_aspek');
		$this->db->join('tbl_sub_praktikum', 'tbl_aspek.kd_sub_praktikum = tbl_sub_praktikum.id_sub_praktikum');
		$this->db->join('tbl_praktikum', 'tbl_praktikum.id_praktikum = tbl_sub_praktikum.kd_praktikum');
		$this->db->where('tbl_aspek.kd_sub_praktikum',$sub_praktikum);
        return $this->db->get()->result_array();*/
		return $this->db->query("select * from tbl_sub_aspek b
									join tbl_aspek c on b.kd_aspek = c.id_aspek
									join tbl_sub_praktikum d on c.kd_sub_praktikum = d.id_sub_praktikum
									join tbl_praktikum e on d.kd_praktikum = e.id_praktikum
									where d.id_sub_praktikum=?
									order by kd_aspek, id_sub_aspek asc",array($sub_praktikum))->result_array();
    }
    
    /*
     * function to add new sub_aspek
     */
    function add_sub_aspek($params)
    {
        $this->db->insert('tbl_sub_aspek',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sub_aspek
     */
    function update_sub_aspek($id_sub_aspek,$params)
    {
        $this->db->where('id_sub_aspek',$id_sub_aspek);
        $response = $this->db->update('tbl_sub_aspek',$params);
        if($response)
        {
            return "sub_aspek updated successfully";
        }
        else
        {
            return "Error occuring while updating sub_aspek";
        }
    }
    
    /*
     * function to delete sub_aspek
     */
    function delete_sub_aspek($id_sub_aspek)
    {
        $response = $this->db->delete('tbl_sub_aspek',array('id_sub_aspek'=>$id_sub_aspek));
        if($response)
        {
            return "sub_aspek deleted successfully";
        }
        else
        {
            return "Error occuring while deleting sub_aspek";
        }
    }
}
