<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login/loginadmin","refresh");
		}
		
        $this->load->model('Admin_model');
    } 

    /*
     * Listing of admin
     */
    function index()
    {
        $data['admin'] = $this->Admin_model->get_all_admin();

        $data['_view'] = 'admin/index';
		$data['judulform'] = 'ADMIN';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new admin
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required');
		$this->form_validation->set_rules('username','Username','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => md5(sha1($this->input->post('password'))),
				'username' => $this->input->post('username'),
				'diinput_oleh' => $_SESSION['username_admin']
            );
            
            $admin_id = $this->Admin_model->add_admin($params);
            redirect('admin/index');
        }
        else
        {            
            $data['_view'] = 'admin/add';
			$data['judulform'] = 'ADMIN';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a admin
     */
    function edit($id_admin)
    {   
        // check if the admin exists before trying to edit it
        $data['admin'] = $this->Admin_model->get_admin($id_admin);
        
        if(isset($data['admin']['id_admin']))
        {
            $this->load->library('form_validation');

			//$this->form_validation->set_rules('password','Password','required');
			$this->form_validation->set_rules('username','Username','required');
		
			if($this->form_validation->run())     
            {   
                if($this->input->post('password')==""){
					$params = array(
						'username' => $this->input->post('username'),
						'diupdate_oleh' => $_SESSION['username_admin'],
					);
				}else{
					$params = array(
						'password' => md5(sha1($this->input->post('password'))),
						'username' => $this->input->post('username'),
						'diupdate_oleh' => $_SESSION['username_admin'],
					);
				}
                $this->Admin_model->update_admin($id_admin,$params);            
                redirect('admin/index');
            }
            else
            {
                $data['_view'] = 'admin/edit';
				
				$data['judulform'] = 'ADMIN';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The admin you are trying to edit does not exist.');
    } 

    /*
     * Deleting admin
     */
    function remove($id_admin)
    {
        if($_SESSION['level_admin']=='su'){
			$admin = $this->Admin_model->get_admin($id_admin);

			// check if the admin exists before trying to delete it
			if(isset($admin['id_admin']))
			{
				$this->Admin_model->delete_admin($id_admin);
				redirect('admin/index');
			}
			else
				show_error('The admin you are trying to delete does not exist.');
		}else{
			redirect("admin","refresh");
		}
    }
    
}
