<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Dosen_mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['kode_dosen']) ? $_SESSION['kode_dosen']:'';
		if($session==""){
			redirect("login/logindosen","refresh");
		}
        $this->load->model('Mahasiswa_model');
		$this->load->model('Nilai_model');
    } 

    /*
     * Listing of mahasiswa
     */
    function index()
    {
        $data['mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi_dosen();

        $data['_view'] = 'dosen_mahasiswa/index';
		$data['judulform'] = 'MAHASISWA';
        $this->load->view('layouts/main_dosen',$data);
    }
	
	/*
     * Listing of nilai mahasiswa
     */
    function nilai($nim=null)
    {
        if($nim<>''){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				$this->load->model('Dosen_model');
				$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
				
				//get nilai 
				$data['all_nilai'] = $this->Nilai_model->get_nilai_praktek_dosen($nim);

				$data['_view'] = 'dosen_mahasiswa/nilai';
				$data['judulform'] = "Nilai Praktek";
				$this->load->view('layouts/main_dosen',$data);
			}else{
				redirect("dosen_mahasiswa","refresh");
			}	
		}else{
			redirect("dosen_mahasiswa","refresh");
		}
    }
	
	/*
     * Listing of detail nilai mahasiswa
     */
	function detail($nim=null, $subpraktikum=null, $id_konf=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->Nilai_model->get_info_mahasiswa_pasien($nim, $subpraktikum, $id_konf);
				
				//get detail nilai 
				$data['detail_nilai'] = $this->Nilai_model->get_nilai_praktek_detail($nim, $subpraktikum, $id_konf);

				$data['_view'] = 'nilai/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('layouts/main_dosen',$data);
			}else{
				redirect("mahasiswa","refresh");
			}	
		}else{
			redirect("mahasiswa","refresh");
		}
    }
	
	/*
     * Listing of print nilai mahasiswa
     */
	function prints($nim=null, $subpraktikum=null, $id_konf=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->Nilai_model->get_info_mahasiswa_pasien($nim, $subpraktikum, $id_konf);
				
				//get detail nilai 
				$data['detail_nilai'] = $this->Nilai_model->get_nilai_praktek_detail($nim, $subpraktikum, $id_konf);

				//$data['_view'] = 'nilai/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('nilai/print',$data);
			}else{
				redirect("mahasiswa","refresh");
			}	
		}else{
			redirect("mahasiswa","refresh");
		}
    }
    
}
