<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Nilai_mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['nim_mhs']) ? $_SESSION['nim_mhs']:'';
		if($session==""){
			redirect("login/loginmahasiswa","refresh");
		}
        $this->load->model('Nilai_mahasiswa_model');
    } 

    /*
     * Listing of nilai mahasiswa
     */
    function index()
    {
		$this->load->model('Mahasiswa_model');
		$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($_SESSION['nim_mhs']);
		if(isset($data['mahasiswa']['id_mahasiswa']))
		{
			//get nilai 
			$data['all_nilai'] = $this->Nilai_mahasiswa_model->get_list_praktek($_SESSION['nim_mhs']);

			$data['_view'] = 'nilai_mahasiswa/index';
			$data['judulform'] = "";
			$this->load->view('layouts/main_mahasiswa',$data);
		}	
    }
	
	/*
     * Listing of detail nilai mahasiswa
     */
	function detail($nim=null, $subpraktikum=null, $id_konf=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->Nilai_mahasiswa_model->get_info_mahasiswa_pasien($_SESSION['nim_mhs'], $subpraktikum, $id_konf);
				
				//get detail nilai 
				$data['detail_nilai'] = $this->Nilai_mahasiswa_model->get_nilai_praktek_detail($_SESSION['nim_mhs'], $subpraktikum, $id_konf);

				$data['_view'] = 'nilai_mahasiswa/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('layouts/main_mahasiswa',$data);
			}else{
				redirect("nilai_mahasiswa","refresh");
			}	
		}
    }
	
	/*
     * Listing of print nilai mahasiswa
     */
	function prints($nim=null, $subpraktikum=null, $id_konf=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->Nilai_mahasiswa_model->get_info_mahasiswa_pasien($_SESSION['nim_mhs'], $subpraktikum, $id_konf);
				
				//get detail nilai 
				$data['detail_nilai'] = $this->Nilai_mahasiswa_model->get_nilai_praktek_detail($_SESSION['nim_mhs'], $subpraktikum, $id_konf);

				//$data['_view'] = 'nilai_mahasiswa/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('nilai_mahasiswa/print',$data);
			}else{
				redirect("nilai_mahasiswa","refresh");
			}	
		}
    }
	
	/*
     * Listing of print nilai mahasiswa
     */
	function printword($nim=null, $subpraktikum=null, $id_konf=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->Nilai_mahasiswa_model->get_info_mahasiswa_pasien($_SESSION['nim_mhs'], $subpraktikum, $id_konf);
				
				//get detail nilai 
				$data['detail_nilai'] = $this->Nilai_mahasiswa_model->get_nilai_praktek_detail($_SESSION['nim_mhs'], $subpraktikum, $id_konf);

				header("Content-type: application/vnd.ms-word");
				header("Content-Disposition: attachment;Filename=document_name.doc");

				//$data['_view'] = 'nilai_mahasiswa/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('nilai_mahasiswa/print',$data);
			}else{
				redirect("nilai_mahasiswa","refresh");
			}	
		}
    }
}
