<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Nilai_praktek extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login/loginadmin","refresh");
		}
        $this->load->model('Nilai_praktek_model');
    } 

    /*
     * Listing of nilai_praktek
     */
    function index()
    {
        
		$this->load->model('Mahasiswa_model');
		$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi();
		
		$this->load->model('Sub_praktikum_model');
		$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();
		
		$this->load->library('form_validation');

		$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		$this->form_validation->set_rules('nim','NIM Mahasiswa','required');
		
		if($this->form_validation->run()){
			$data['nilai_praktek'] = $this->Nilai_praktek_model->get_all_nilai_praktek_cari($this->input->post('nim',TRUE), $this->input->post('kd_sub_praktikum',TRUE));
		}else{
			$data['nilai_praktek'] = $this->Nilai_praktek_model->get_all_nilai_praktek();
		}
        $data['_view'] = 'nilai_praktek/index';
		$data['judulform'] = 'NILAI PRAKTEK';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new nilai_praktek
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tanggal_praktek','Tanggal Praktek','required');
		$this->form_validation->set_rules('nim','NIM Mahasiswa','required');
		$this->form_validation->set_rules('nik','NIK Pasien','required');
		$this->form_validation->set_rules('kode_dosen','Nama Dosen','required');
		$this->form_validation->set_rules('kd_sub_aspek','Kd Sub Aspek','required');
		$this->form_validation->set_rules('angka_perolehan','Angka Perolehan','required');
		$this->form_validation->set_rules('kd_konfigurasi','Thn Akademik & Semester','required');
		//$this->form_validation->set_rules('validasi_dosen','Validasi Dosen','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nim' => $this->input->post('nim',TRUE),
				'nik' => $this->input->post('nik',TRUE),
				'kd_sub_aspek' => $this->input->post('kd_sub_aspek',TRUE),
				'kode_dosen' => $this->input->post('kode_dosen',TRUE),
				'tanggal_praktek' => $this->input->post('tanggal_praktek',TRUE),
				'angka_perolehan' => $this->input->post('angka_perolehan',TRUE),
				'tanggal_input' => $this->input->post('tanggal_input',TRUE),
				'kd_konfigurasi' => $this->input->post('kd_konfigurasi',TRUE),
				//'validasi_dosen' => $this->input->post('validasi_dosen',TRUE),
				//'tanggal_validasi' => $this->input->post('tanggal_validasi',TRUE),
				'tanggal_input' => date('Y-m-d'),
				'diinput_oleh' => $_SESSION['username_admin'],
				//'diupdate_oleh' => $this->input->post('diupdate_oleh',TRUE),
            );
            
            $nilai_praktek_id = $this->Nilai_praktek_model->add_nilai_praktek($params);
            redirect('nilai_praktek/index');
        }
        else
        {
			$this->load->model('M_konfigurasi_model');
			$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
			
			$this->load->model('Dosen_model');
			$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
			
			$this->load->model('Mahasiswa_model');
			$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa();

			$this->load->model('Pasien_model');
			$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

			$this->load->model('Sub_aspek_model');
			$data['all_sub_aspek'] = $this->Sub_aspek_model->get_all_sub_aspek();
            
            $data['_view'] = 'nilai_praktek/add';
			$data['judulform'] = 'NILAI PRAKTEK';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a nilai_praktek
     */
    function edit($id_nilai_praktek)
    {   
        // check if the nilai_praktek exists before trying to edit it
        $data['nilai_praktek'] = $this->Nilai_praktek_model->get_nilai_praktek($id_nilai_praktek);
        
        if(isset($data['nilai_praktek']['id_nilai_praktek']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tanggal_praktek','Tanggal Praktek','required');
			$this->form_validation->set_rules('nim','NIM Mahasiswa','required');
			$this->form_validation->set_rules('nik','NIK Pasien','required');
			$this->form_validation->set_rules('kode_dosen','Nama Dosen','required');
			$this->form_validation->set_rules('kd_sub_aspek','Kd Sub Aspek','required');
			$this->form_validation->set_rules('angka_perolehan','Angka Perolehan','required');
			//$this->form_validation->set_rules('validasi_dosen','Validasi Dosen','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nim' => $this->input->post('nim',TRUE),
					'nik' => $this->input->post('nik',TRUE),
					'kd_sub_aspek' => $this->input->post('kd_sub_aspek',TRUE),
					'kode_dosen' => $this->input->post('kode_dosen',TRUE),
					//'validasi_dosen' => $this->input->post('validasi_dosen'),
					'tanggal_praktek' => $this->input->post('tanggal_praktek',TRUE),
					'angka_perolehan' => $this->input->post('angka_perolehan',TRUE),
					//'tanggal_input' => $this->input->post('tanggal_input'),
					'kd_konfigurasi' => $this->input->post('kd_konfigurasi',TRUE),
					//'tanggal_validasi' => $this->input->post('tanggal_validasi'),
					//'diinput_oleh' => $this->input->post('diinput_oleh'),
					'diupdate_oleh' => date('Y-m-d'),
                );

                $this->Nilai_praktek_model->update_nilai_praktek($id_nilai_praktek,$params);            
                redirect('nilai_praktek/index');
            }
            else
            {
				$this->load->model('M_konfigurasi_model');
				$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
			
				$this->load->model('Dosen_model');
				$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
			
				$this->load->model('Mahasiswa_model');
				$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa();

				$this->load->model('Pasien_model');
				$data['all_pasien'] = $this->Pasien_model->get_all_pasien();

				$this->load->model('Sub_aspek_model');
				$data['all_sub_aspek'] = $this->Sub_aspek_model->get_all_sub_aspek();

                $data['_view'] = 'nilai_praktek/edit';
				$data['judulform'] = 'NILAI PRAKTEK';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The nilai_praktek you are trying to edit does not exist.');
    } 

    /*
     * Deleting nilai_praktek
     */
    function remove($id_nilai_praktek)
    {
        $nilai_praktek = $this->Nilai_praktek_model->get_nilai_praktek($id_nilai_praktek);

        // check if the nilai_praktek exists before trying to delete it
        if(isset($nilai_praktek['id_nilai_praktek']))
        {
            $this->Nilai_praktek_model->delete_nilai_praktek($id_nilai_praktek);
            redirect('nilai_praktek/index');
        }
        else
            show_error('The nilai_praktek you are trying to delete does not exist.');
    }
    
}
