<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Nilai extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login/loginadmin","refresh");
		}
        $this->load->model('Nilai_model');
    } 

    /*
     * Listing of nilai mahasiswa
     */
    function index($nim=null)
    {
        if($nim<>''){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				$this->load->model('Dosen_model');
				$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
				
				//get nilai 
				$data['all_nilai'] = $this->Nilai_model->get_nilai_praktek($nim);

				$data['_view'] = 'nilai/index';
				$data['judulform'] = "Nilai Praktek";
				$this->load->view('layouts/main',$data);
			}else{
				redirect("mahasiswa","refresh");
			}	
		}else{
			redirect("mahasiswa","refresh");
		}
    }
	
	/*
     * Listing of detail nilai mahasiswa
     */
	function detail($nim=null, $subpraktikum=null, $id_konf=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->Nilai_model->get_info_mahasiswa_pasien($nim, $subpraktikum, $id_konf);
				
				//get detail nilai 
				$data['detail_nilai'] = $this->Nilai_model->get_nilai_praktek_detail($nim, $subpraktikum, $id_konf);

				$data['_view'] = 'nilai/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('layouts/main',$data);
			}else{
				redirect("mahasiswa","refresh");
			}	
		}else{
			redirect("mahasiswa","refresh");
		}
    }
	
	/*
     * Listing of print nilai mahasiswa
     */
	function prints($nim=null, $subpraktikum=null, $id_konf=null)
    {
        if(($nim<>'')and($subpraktikum<>'')and($id_konf<>'')){
			$this->load->model('Mahasiswa_model');
			$data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa_nim($nim);
			if(isset($data['mahasiswa']['id_mahasiswa']))
			{
				//get detail info mahasiswa dan pasien
				$data['info'] = $this->Nilai_model->get_info_mahasiswa_pasien($nim, $subpraktikum, $id_konf);
				
				//get detail nilai 
				$data['detail_nilai'] = $this->Nilai_model->get_nilai_praktek_detail($nim, $subpraktikum, $id_konf);

				//$data['_view'] = 'nilai/detail';
				$data['judulform'] = "Detail Nilai Praktek";
				$this->load->view('nilai/print',$data);
			}else{
				redirect("mahasiswa","refresh");
			}	
		}else{
			redirect("mahasiswa","refresh");
		}
    }
    
	/*
     * Adding a new nilai_praktek
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_konf','Thn Akademik & Semester','required');
		$this->form_validation->set_rules('nim','Nim','required');
		$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		
		if($this->form_validation->run())     
        {   
            /*$params = array(
				'id_konf' => $this->input->post('id_konf', TRUE),
				'nim' => $this->input->post('nim', TRUE),
				'kd_sub_praktikum' => $this->input->post('kd_sub_praktikum', TRUE),
            );*/
			
			$this->load->model('M_konfigurasi_model');
			$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
			
			$this->load->model('Mahasiswa_model');
			$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi();

			$this->load->model('Dosen_model');
			$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
			
			$this->load->model('Sub_praktikum_model');
			$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();
			
			$this->load->model('Sub_aspek_model');
			$data['sub_aspek'] = $this->Sub_aspek_model->get_all_sub_aspek_sub_praktikum($this->input->post('kd_sub_praktikum', TRUE));
			
			//get detail info mahasiswa dan pasien
			$data['info'] = $this->Nilai_model->get_info_mahasiswa_pasien($this->input->post('nim', TRUE), $this->input->post('kd_sub_praktikum', TRUE), $this->input->post('id_konf', TRUE));
			
			//get detail nilai 
			$data['detail_nilai'] = $this->Nilai_model->get_nilai_praktek_detail($this->input->post('nim', TRUE), $this->input->post('kd_sub_praktikum', TRUE), $this->input->post('id_konf', TRUE));
			
			if(!isset($data['detail_nilai']['nim'])){
				$this->load->model('Pasien_model');
				$data['all_pasien'] = $this->Pasien_model->get_all_pasien();
            }
			//set 1 untuk form input nilai
			$data['form_nilai'] = 1;
			
            $data['_view'] = 'nilai/add';
			$data['judulform'] = 'NILAI PRAKTEK';
            $this->load->view('layouts/main',$data);
        }
        else
        {
			$this->load->model('Dosen_model');
			$data['all_dosen'] = $this->Dosen_model->get_all_dosen();
			
			$this->load->model('M_konfigurasi_model');
			$data['all_konfigurasi'] = $this->M_konfigurasi_model->get_all_tbl_konfigurasi();
			
			$this->load->model('Mahasiswa_model');
			$data['all_mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa_gigi();

			$this->load->model('Sub_praktikum_model');
			$data['all_sub_praktikum'] = $this->Sub_praktikum_model->get_all_sub_praktikum();
			
			$data['form_nilai'] = 0;
            
            $data['_view'] = 'nilai/add';
			$data['judulform'] = 'NILAI PRAKTEK';
            $this->load->view('layouts/main',$data);
        }
    }

	function addpraktikum()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_konf','Thn Akademik & Semester','required');
		$this->form_validation->set_rules('nim','Nama Mahasiswa','required');
		$this->form_validation->set_rules('nik','Nama Pasien','required');
		$this->form_validation->set_rules('kode_dosen','Nama Dosen','required');
		$this->form_validation->set_rules('tanggal_praktek','Tanggal Praktek','required');
		$this->form_validation->set_rules('jumlah','Jumlah Sub Aspek','required');
		$this->form_validation->set_rules('kd_sub_praktikum','Sub Praktikum','required');
		
		if($this->form_validation->run())     
        {   
            // insert ke tabel diagnosa
			$params_diagnosa = array(
									'id_sub_praktikum' 	=> $this->input->post('kd_sub_praktikum', TRUE),
									'nik_pasien' 		=> $this->input->post('nik', TRUE),
									'nim' 				=> $this->input->post('nim', TRUE),
									'diagnosa' 			=> $this->input->post('diagnosa', TRUE),
									'diinput_oleh' 		=> $_SESSION['username_admin']
									);
			$this->db->insert('tbl_diagnosa', $params_diagnosa);
			
			// insert ke tabel nilai praktek
			$this->db->trans_begin();
			$params = array();
			for($i=1;$i<$this->input->post('jumlah', TRUE);$i++){
				$params[$i]['tanggal_praktek'] 		= $this->input->post('tanggal_praktek', TRUE);
				$params[$i]['nim'] 					= $this->input->post('nim', TRUE);
				$params[$i]['nik'] 					= $this->input->post('nik', TRUE);
				$params[$i]['kode_dosen'] 			= $this->input->post('kode_dosen', TRUE);
				$params[$i]['kd_sub_aspek'] 		= $_POST['kd_sub_aspek'.$i];
				$params[$i]['angka_perolehan'] 		= $_POST['angka_perolehan'.$i];
				$params[$i]['tanggal_input'] 		= date('Y-m-d');
				$params[$i]['kd_konfigurasi'] 		= $this->input->post('id_konf', TRUE);
				$params[$i]['diinput_oleh'] 		= $_SESSION['username_admin'];
			}
			$this->db->insert_batch('tbl_nilai_praktek', $params);
			
			
			if ($this->db->trans_status() === FALSE){
				$this->db->trans_rollback();
				echo "<script>alert('Gagal disimpan!!!'); window.history.back();</script>";
			} else {
				$this->db->trans_commit();
				echo "<script>alert('Berhasil disimpan!!!'); </script>";
				$this->session->set_flashdata('success', 'Nilai sudah ditambahkan');
			}
			$this->db->trans_complete();
			
			
			redirect('nilai/add');
		}
	}		
}
