<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Password_dosen extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['kode_dosen']) ? $_SESSION['kode_dosen']:'';
		if($session==""){
			redirect("login/logindosen","refresh");
		}
    } 

    /*
     * Data of password dosen
     */
    function index()
    {
		$data['_view'] = 'password_dosen/index';
		$data['judulform'] = "";
		$this->load->view('layouts/main_dosen',$data);
    }
	
	/*
     * Editing a password dosen
     */
    function edit()
    {   
        if(isset($_SESSION['kode_dosen']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('kode_dosen','Kode Dosen','required');
			$this->form_validation->set_rules('password_lama','Password Lama','required');
			$this->form_validation->set_rules('password_baru','Password Baru','required');
		
			if($this->form_validation->run())     
            {   
				//check old password 
				$pwd_lama = md5(sha1($this->input->post('password_lama',TRUE)));
				$sql = $this->db->query("select * from tbl_dosen where kode_dosen=? and password=?", array($_SESSION['kode_dosen'], $pwd_lama))->num_rows();
				if($sql > 0){
					$pwd_baru = md5(sha1($this->input->post('password_baru',TRUE)));
					$this->db->query("update tbl_dosen set password=? where kode_dosen=?", array($pwd_baru, $_SESSION['kode_dosen']));
					$this->session->set_flashdata('success', 'Password berhasil diubah.');
					redirect('password_dosen/index');
				}else{
					$this->session->set_flashdata('error', 'Password lama tidak sama.');
					$data['_view'] = 'password_dosen/index';
					$data['judulform'] = "Ubah Password";
					$this->load->view('layouts/main_dosen',$data);
				}
            }else{
				$data['_view'] = 'password_dosen/index';
				$data['judulform'] = "Ubah Password";
				$this->load->view('layouts/main_dosen',$data);
			}
        }
        else
            show_error('The dosen you are trying to edit does not exist.');
    } 
}
