<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Password_admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['username_admin']) ? $_SESSION['username_admin']:'';
		if($session==""){
			redirect("login/loginadmin","refresh");
		}
    } 

    /*
     * Data of password admin
     */
    function index()
    {
		$data['_view'] = 'password_admin/index';
		$data['judulform'] = "";
		$this->load->view('layouts/main',$data);
    }
	
	/*
     * Editing a password admin
     */
    function edit()
    {   
        if(isset($_SESSION['username_admin']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('username','Username','required');
			$this->form_validation->set_rules('password_lama','Password Lama','required');
			$this->form_validation->set_rules('password_baru','Password Baru','required');
		
			if($this->form_validation->run())     
            {   
				//check old password 
				$pwd_lama = md5(sha1($this->input->post('password_lama',TRUE)));
				$sql = $this->db->query("select * from tbl_admin where username=? and password=?", array($_SESSION['username_admin'], $pwd_lama))->num_rows();
				if($sql > 0){
					$pwd_baru = md5(sha1($this->input->post('password_baru',TRUE)));
					$this->db->query("update tbl_admin set password=? where username=?", array($pwd_baru, $_SESSION['username_admin']));
					$this->session->set_flashdata('success', 'Password berhasil diubah.');
					redirect('password_admin/index');
				}else{
					$this->session->set_flashdata('error', 'Password lama tidak sama.');
					$data['_view'] = 'password_admin/index';
					$data['judulform'] = "Ubah Password";
					$this->load->view('layouts/main',$data);
				}
            }else{
				$data['_view'] = 'password_admin/index';
				$data['judulform'] = "Ubah Password";
				$this->load->view('layouts/main',$data);
			}
        }
        else
            show_error('The admin you are trying to edit does not exist.');
    } 
}
