<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Password_mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$session = isset($_SESSION['nim_mhs']) ? $_SESSION['nim_mhs']:'';
		if($session==""){
			redirect("login/loginmahasiswa","refresh");
		}
    } 

    /*
     * Data of password mahasiswa
     */
    function index()
    {
		$data['_view'] = 'password_mahasiswa/index';
		$data['judulform'] = "";
		$this->load->view('layouts/main_mahasiswa',$data);
    }
	
	/*
     * Editing a password mahasiswa
     */
    function edit()
    {   
        if(isset($_SESSION['nim_mhs']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('nim','NIM','required');
			$this->form_validation->set_rules('password_lama','Password Lama','required');
			$this->form_validation->set_rules('password_baru','Password Baru','required');
		
			if($this->form_validation->run())     
            {   
				//check old password 
				$pwd_lama = md5(sha1($this->input->post('password_lama',TRUE)));
				$sql = $this->db->query("select * from tbl_mahasiswa where nim=? and password=?", array($_SESSION['nim_mhs'], $pwd_lama))->num_rows();
				if($sql > 0){
					$pwd_baru = md5(sha1($this->input->post('password_baru',TRUE)));
					$this->db->query("update tbl_mahasiswa set password=? where nim=?", array($pwd_baru, $_SESSION['nim_mhs']));
					$this->session->set_flashdata('success', 'Password berhasil diubah.');
					redirect('password_mahasiswa/index');
				}else{
					$this->session->set_flashdata('error', 'Password lama tidak sama.');
					$data['_view'] = 'password_mahasiswa/index';
					$data['judulform'] = "Ubah Password";
					$this->load->view('layouts/main_mahasiswa',$data);
				}
            }else{
				$data['_view'] = 'password_mahasiswa/index';
				$data['judulform'] = "Ubah Password";
				$this->load->view('layouts/main_mahasiswa',$data);
			}
        }
        else
            show_error('The dosen you are trying to edit does not exist.');
    } 
}
