<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Dosen_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dosen by id_dosen
     */
    function get_dosen($id_dosen)
    {
        return $this->db->get_where('tbl_dosen',array('id_dosen'=>$id_dosen))->row_array();
    }
    
    /*
     * Get all dosen
     */
    function get_all_dosen()
    {
        return $this->db->query('select * from tbl_dosen order by nama_dosen asc')->result_array();
    }
    
    /*
     * function to add new dosen
     */
    function add_dosen($params)
    {
        $this->db->insert('tbl_dosen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dosen
     */
    function update_dosen($id_dosen,$params)
    {
        $this->db->where('id_dosen',$id_dosen);
        $response = $this->db->update('tbl_dosen',$params);
        if($response)
        {
            return "dosen updated successfully";
        }
        else
        {
            return "Error occuring while updating dosen";
        }
    }
    
    /*
     * function to delete dosen
     */
    function delete_dosen($id_dosen)
    {
        $response = $this->db->delete('tbl_dosen',array('id_dosen'=>$id_dosen));
        if($response)
        {
            return "dosen deleted successfully";
        }
        else
        {
            return "Error occuring while deleting dosen";
        }
    }
	
	public function upload_data($filename){
        ini_set('memory_limit', '-1');
        $inputFileName = './excels/'.$filename;
        try {
        $objPHPExcel = PHPExcel_IOFactory::load($inputFileName);
        } catch(Exception $e) {
        die('Error loading file :' . $e->getMessage());
        }

        $worksheet = $objPHPExcel->getActiveSheet()->toArray(null,true,true,true);
        $numRows = count($worksheet);

        for ($i=2; $i < ($numRows+1) ; $i++) { 
            $ins = array(
                    "kode_dosen"    => $worksheet[$i]["A"],
                    "nama_dosen"   	=> $worksheet[$i]["B"],
					"jk"   			=> $worksheet[$i]["C"],
					"password"   	=> md5(sha1($worksheet[$i]["A"])),
					"level"   		=> $worksheet[$i]["D"],
					"diinput_oleh" 	=> $_SESSION['username_admin']
                   );

            $this->db->insert('tbl_dosen', $ins);
        }
    }
}
