<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Konfigurasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get konfigurasi by id_konf
     */
    function get_konfigurasi($id_konf)
    {
        return $this->db->get_where('tbl_konfigurasi',array('id_konf'=>$id_konf))->row_array();
    }
    
    /*
     * Get all konfigurasi
     */
    function get_all_konfigurasi()
    {
        return $this->db->get('tbl_konfigurasi')->result_array();
    }
    
    /*
     * function to add new konfigurasi
     */
    function add_konfigurasi($params)
    {
        $this->db->insert('tbl_konfigurasi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update konfigurasi
     */
    function update_konfigurasi($id_konf,$params)
    {
        $this->db->where('id_konf',$id_konf);
        $response = $this->db->update('tbl_konfigurasi',$params);
        if($response)
        {
            return "konfigurasi updated successfully";
        }
        else
        {
            return "Error occuring while updating konfigurasi";
        }
    }
    
    /*
     * function to delete konfigurasi
     */
    function delete_konfigurasi($id_konf)
    {
        $response = $this->db->delete('tbl_konfigurasi',array('id_konf'=>$id_konf));
        if($response)
        {
            return "konfigurasi deleted successfully";
        }
        else
        {
            return "Error occuring while deleting konfigurasi";
        }
    }
}
