<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class M_konfigurasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_konfigurasi by id_konf
     */
    function get_tbl_konfigurasi($id_konf)
    {
        return $this->db->get_where('tbl_konfigurasi',array('id_konf'=>$id_konf))->row_array();
    }
    
    /*
     * Get tbl_konfigurasi aktif
     */
    function get_tbl_konfigurasi_aktif()
    {
        //return $this->db->get('tbl_konfigurasi')->result_array();
		return $this->db->query("select * from tbl_konfigurasi where status ='A'")->result_array();
    }
	
	/*
     * Get all tbl_konfigurasi
     */
    function get_all_tbl_konfigurasi()
    {
        return $this->db->query('select * from tbl_konfigurasi order by thn_akademik DESC, kd_semester DESC')->result_array();
    }
    
    /*
     * function to add new tbl_konfigurasi
     */
    function add_tbl_konfigurasi($params)
    {
        $this->db->insert('tbl_konfigurasi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_konfigurasi
     */
    function update_tbl_konfigurasi($id_konf,$params)
    {
        $this->db->where('id_konf',$id_konf);
        $this->db->update('tbl_konfigurasi',$params);
    }
    
    /*
     * function to delete tbl_konfigurasi
     */
    function delete_tbl_konfigurasi($id_konf)
    {
        $this->db->delete('tbl_konfigurasi',array('id_konf'=>$id_konf));
    }
}
