<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Praktikum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get praktikum by id_praktikum
     */
    function get_praktikum($id_praktikum)
    {
        return $this->db->get_where('tbl_praktikum',array('id_praktikum'=>$id_praktikum))->row_array();
    }
    
    /*
     * Get all praktikum
     */
    function get_all_praktikum()
    {
        $this->db->order_by('nama_praktikum', 'ASC');
		return $this->db->get('tbl_praktikum')->result_array();
    }
    
    /*
     * function to add new praktikum
     */
    function add_praktikum($params)
    {
        $this->db->insert('tbl_praktikum',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update praktikum
     */
    function update_praktikum($id_praktikum,$params)
    {
        $this->db->where('id_praktikum',$id_praktikum);
        $response = $this->db->update('tbl_praktikum',$params);
        if($response)
        {
            return "praktikum updated successfully";
        }
        else
        {
            return "Error occuring while updating praktikum";
        }
    }
    
    /*
     * function to delete praktikum
     */
    function delete_praktikum($id_praktikum)
    {
        $response = $this->db->delete('tbl_praktikum',array('id_praktikum'=>$id_praktikum));
        if($response)
        {
            return "praktikum deleted successfully";
        }
        else
        {
            return "Error occuring while deleting praktikum";
        }
    }
}
